version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: 1source-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  1source-integration:
    build:
      context: ./
      dockerfile: Dockerfile
    image: onesource:latest
    container_name: 1source-integration
    #    restart: on-failure
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - postgres