/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * BasisDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-23T11:29:17.054Z")
public class BasisDTO {
  @JsonProperty("basisId")
  private Integer basisId = null;

  @JsonProperty("basisName")
  private String basisName = null;

  public BasisDTO basisId(Integer basisId) {
    this.basisId = basisId;
    return this;
  }

   /**
   * Get basisId
   * @return basisId
  **/
  @ApiModelProperty(value = "")
  public Integer getBasisId() {
    return basisId;
  }

  public void setBasisId(Integer basisId) {
    this.basisId = basisId;
  }

  public BasisDTO basisName(String basisName) {
    this.basisName = basisName;
    return this;
  }

   /**
   * Get basisName
   * @return basisName
  **/
  @ApiModelProperty(value = "")
  public String getBasisName() {
    return basisName;
  }

  public void setBasisName(String basisName) {
    this.basisName = basisName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasisDTO basisDTO = (BasisDTO) o;
    return Objects.equals(this.basisId, basisDTO.basisId) &&
        Objects.equals(this.basisName, basisDTO.basisName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basisId, basisName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasisDTO {\n");
    
    sb.append("    basisId: ").append(toIndentedString(basisId)).append("\n");
    sb.append("    basisName: ").append(toIndentedString(basisName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

