/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BulkTradeInputDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-01-07T21:15:14.632Z")
public class BulkTradeInputDTO {
  @JsonProperty("__qualifiedName")
  private String qualifiedName = null;

  @JsonProperty("tradeInputDTOs")
  private List<PositionTradeInputDTO> tradeInputDTOs = null;

  public BulkTradeInputDTO qualifiedName(String qualifiedName) {
    this.qualifiedName = qualifiedName;
    return this;
  }

   /**
   * Get qualifiedName
   * @return qualifiedName
  **/
  @ApiModelProperty(value = "")
  public String getQualifiedName() {
    return qualifiedName;
  }

  public void setQualifiedName(String qualifiedName) {
    this.qualifiedName = qualifiedName;
  }

  public BulkTradeInputDTO tradeInputDTOs(List<PositionTradeInputDTO> tradeInputDTOs) {
    this.tradeInputDTOs = tradeInputDTOs;
    return this;
  }

  public BulkTradeInputDTO addTradeInputDTOsItem(PositionTradeInputDTO tradeInputDTOsItem) {
    if (this.tradeInputDTOs == null) {
      this.tradeInputDTOs = new ArrayList<>();
    }
    this.tradeInputDTOs.add(tradeInputDTOsItem);
    return this;
  }

   /**
   * Get tradeInputDTOs
   * @return tradeInputDTOs
  **/
  @ApiModelProperty(value = "")
  public List<PositionTradeInputDTO> getTradeInputDTOs() {
    return tradeInputDTOs;
  }

  public void setTradeInputDTOs(List<PositionTradeInputDTO> tradeInputDTOs) {
    this.tradeInputDTOs = tradeInputDTOs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkTradeInputDTO bulkTradeInputDTO = (BulkTradeInputDTO) o;
    return Objects.equals(this.qualifiedName, bulkTradeInputDTO.qualifiedName) &&
        Objects.equals(this.tradeInputDTOs, bulkTradeInputDTO.tradeInputDTOs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qualifiedName, tradeInputDTOs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkTradeInputDTO {\n");
    
    sb.append("    qualifiedName: ").append(toIndentedString(qualifiedName)).append("\n");
    sb.append("    tradeInputDTOs: ").append(toIndentedString(tradeInputDTOs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

