/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CategoryDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-20T15:00:33.025Z")
public class CategoryDTO {
  @JsonProperty("category0Id")
  private Integer category0Id = null;

  @JsonProperty("category0Name")
  private String category0Name = null;

  @JsonProperty("category1Id")
  private Integer category1Id = null;

  @JsonProperty("category1Name")
  private String category1Name = null;

  @JsonProperty("category2Id")
  private Integer category2Id = null;

  @JsonProperty("category2Name")
  private String category2Name = null;

  @JsonProperty("category3Id")
  private Integer category3Id = null;

  @JsonProperty("category3Name")
  private String category3Name = null;

  @JsonProperty("category4Id")
  private Integer category4Id = null;

  @JsonProperty("category4Name")
  private String category4Name = null;

  @JsonProperty("category5Id")
  private Integer category5Id = null;

  @JsonProperty("category5Name")
  private String category5Name = null;

  @JsonProperty("categoryId")
  private Integer categoryId = null;

  @JsonProperty("categoryLevel")
  private Integer categoryLevel = null;

  @JsonProperty("categoryName")
  private String categoryName = null;

  @JsonProperty("clientCat1Name")
  private String clientCat1Name = null;

  @JsonProperty("defaultDrf")
  private Double defaultDrf = null;

  @JsonProperty("isitClass")
  private String isitClass = null;

  @JsonProperty("monthEndSortTitle")
  private String monthEndSortTitle = null;

  @JsonProperty("monthEndSortValue")
  private String monthEndSortValue = null;

  @JsonProperty("parentId")
  private Integer parentId = null;

  @JsonProperty("priceFactor")
  private Integer priceFactor = null;

  @JsonProperty("sortTitle")
  private String sortTitle = null;

  @JsonProperty("sortValue")
  private String sortValue = null;

  public CategoryDTO category0Id(Integer category0Id) {
    this.category0Id = category0Id;
    return this;
  }

   /**
   * Get category0Id
   * @return category0Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory0Id() {
    return category0Id;
  }

  public void setCategory0Id(Integer category0Id) {
    this.category0Id = category0Id;
  }

  public CategoryDTO category0Name(String category0Name) {
    this.category0Name = category0Name;
    return this;
  }

   /**
   * Get category0Name
   * @return category0Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory0Name() {
    return category0Name;
  }

  public void setCategory0Name(String category0Name) {
    this.category0Name = category0Name;
  }

  public CategoryDTO category1Id(Integer category1Id) {
    this.category1Id = category1Id;
    return this;
  }

   /**
   * Get category1Id
   * @return category1Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory1Id() {
    return category1Id;
  }

  public void setCategory1Id(Integer category1Id) {
    this.category1Id = category1Id;
  }

  public CategoryDTO category1Name(String category1Name) {
    this.category1Name = category1Name;
    return this;
  }

   /**
   * Get category1Name
   * @return category1Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory1Name() {
    return category1Name;
  }

  public void setCategory1Name(String category1Name) {
    this.category1Name = category1Name;
  }

  public CategoryDTO category2Id(Integer category2Id) {
    this.category2Id = category2Id;
    return this;
  }

   /**
   * Get category2Id
   * @return category2Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory2Id() {
    return category2Id;
  }

  public void setCategory2Id(Integer category2Id) {
    this.category2Id = category2Id;
  }

  public CategoryDTO category2Name(String category2Name) {
    this.category2Name = category2Name;
    return this;
  }

   /**
   * Get category2Name
   * @return category2Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory2Name() {
    return category2Name;
  }

  public void setCategory2Name(String category2Name) {
    this.category2Name = category2Name;
  }

  public CategoryDTO category3Id(Integer category3Id) {
    this.category3Id = category3Id;
    return this;
  }

   /**
   * Get category3Id
   * @return category3Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory3Id() {
    return category3Id;
  }

  public void setCategory3Id(Integer category3Id) {
    this.category3Id = category3Id;
  }

  public CategoryDTO category3Name(String category3Name) {
    this.category3Name = category3Name;
    return this;
  }

   /**
   * Get category3Name
   * @return category3Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory3Name() {
    return category3Name;
  }

  public void setCategory3Name(String category3Name) {
    this.category3Name = category3Name;
  }

  public CategoryDTO category4Id(Integer category4Id) {
    this.category4Id = category4Id;
    return this;
  }

   /**
   * Get category4Id
   * @return category4Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory4Id() {
    return category4Id;
  }

  public void setCategory4Id(Integer category4Id) {
    this.category4Id = category4Id;
  }

  public CategoryDTO category4Name(String category4Name) {
    this.category4Name = category4Name;
    return this;
  }

   /**
   * Get category4Name
   * @return category4Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory4Name() {
    return category4Name;
  }

  public void setCategory4Name(String category4Name) {
    this.category4Name = category4Name;
  }

  public CategoryDTO category5Id(Integer category5Id) {
    this.category5Id = category5Id;
    return this;
  }

   /**
   * Get category5Id
   * @return category5Id
  **/
  @ApiModelProperty(value = "")
  public Integer getCategory5Id() {
    return category5Id;
  }

  public void setCategory5Id(Integer category5Id) {
    this.category5Id = category5Id;
  }

  public CategoryDTO category5Name(String category5Name) {
    this.category5Name = category5Name;
    return this;
  }

   /**
   * Get category5Name
   * @return category5Name
  **/
  @ApiModelProperty(value = "")
  public String getCategory5Name() {
    return category5Name;
  }

  public void setCategory5Name(String category5Name) {
    this.category5Name = category5Name;
  }

  public CategoryDTO categoryId(Integer categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Get categoryId
   * @return categoryId
  **/
  @ApiModelProperty(value = "")
  public Integer getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Integer categoryId) {
    this.categoryId = categoryId;
  }

  public CategoryDTO categoryLevel(Integer categoryLevel) {
    this.categoryLevel = categoryLevel;
    return this;
  }

   /**
   * Get categoryLevel
   * @return categoryLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getCategoryLevel() {
    return categoryLevel;
  }

  public void setCategoryLevel(Integer categoryLevel) {
    this.categoryLevel = categoryLevel;
  }

  public CategoryDTO categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Get categoryName
   * @return categoryName
  **/
  @ApiModelProperty(value = "")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public CategoryDTO clientCat1Name(String clientCat1Name) {
    this.clientCat1Name = clientCat1Name;
    return this;
  }

   /**
   * Get clientCat1Name
   * @return clientCat1Name
  **/
  @ApiModelProperty(value = "")
  public String getClientCat1Name() {
    return clientCat1Name;
  }

  public void setClientCat1Name(String clientCat1Name) {
    this.clientCat1Name = clientCat1Name;
  }

  public CategoryDTO defaultDrf(Double defaultDrf) {
    this.defaultDrf = defaultDrf;
    return this;
  }

   /**
   * Get defaultDrf
   * @return defaultDrf
  **/
  @ApiModelProperty(value = "")
  public Double getDefaultDrf() {
    return defaultDrf;
  }

  public void setDefaultDrf(Double defaultDrf) {
    this.defaultDrf = defaultDrf;
  }

  public CategoryDTO isitClass(String isitClass) {
    this.isitClass = isitClass;
    return this;
  }

   /**
   * Get isitClass
   * @return isitClass
  **/
  @ApiModelProperty(value = "")
  public String getIsitClass() {
    return isitClass;
  }

  public void setIsitClass(String isitClass) {
    this.isitClass = isitClass;
  }

  public CategoryDTO monthEndSortTitle(String monthEndSortTitle) {
    this.monthEndSortTitle = monthEndSortTitle;
    return this;
  }

   /**
   * Get monthEndSortTitle
   * @return monthEndSortTitle
  **/
  @ApiModelProperty(value = "")
  public String getMonthEndSortTitle() {
    return monthEndSortTitle;
  }

  public void setMonthEndSortTitle(String monthEndSortTitle) {
    this.monthEndSortTitle = monthEndSortTitle;
  }

  public CategoryDTO monthEndSortValue(String monthEndSortValue) {
    this.monthEndSortValue = monthEndSortValue;
    return this;
  }

   /**
   * Get monthEndSortValue
   * @return monthEndSortValue
  **/
  @ApiModelProperty(value = "")
  public String getMonthEndSortValue() {
    return monthEndSortValue;
  }

  public void setMonthEndSortValue(String monthEndSortValue) {
    this.monthEndSortValue = monthEndSortValue;
  }

  public CategoryDTO parentId(Integer parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @ApiModelProperty(value = "")
  public Integer getParentId() {
    return parentId;
  }

  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  public CategoryDTO priceFactor(Integer priceFactor) {
    this.priceFactor = priceFactor;
    return this;
  }

   /**
   * Get priceFactor
   * @return priceFactor
  **/
  @ApiModelProperty(value = "")
  public Integer getPriceFactor() {
    return priceFactor;
  }

  public void setPriceFactor(Integer priceFactor) {
    this.priceFactor = priceFactor;
  }

  public CategoryDTO sortTitle(String sortTitle) {
    this.sortTitle = sortTitle;
    return this;
  }

   /**
   * Get sortTitle
   * @return sortTitle
  **/
  @ApiModelProperty(value = "")
  public String getSortTitle() {
    return sortTitle;
  }

  public void setSortTitle(String sortTitle) {
    this.sortTitle = sortTitle;
  }

  public CategoryDTO sortValue(String sortValue) {
    this.sortValue = sortValue;
    return this;
  }

   /**
   * Get sortValue
   * @return sortValue
  **/
  @ApiModelProperty(value = "")
  public String getSortValue() {
    return sortValue;
  }

  public void setSortValue(String sortValue) {
    this.sortValue = sortValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryDTO categoryDTO = (CategoryDTO) o;
    return Objects.equals(this.category0Id, categoryDTO.category0Id) &&
        Objects.equals(this.category0Name, categoryDTO.category0Name) &&
        Objects.equals(this.category1Id, categoryDTO.category1Id) &&
        Objects.equals(this.category1Name, categoryDTO.category1Name) &&
        Objects.equals(this.category2Id, categoryDTO.category2Id) &&
        Objects.equals(this.category2Name, categoryDTO.category2Name) &&
        Objects.equals(this.category3Id, categoryDTO.category3Id) &&
        Objects.equals(this.category3Name, categoryDTO.category3Name) &&
        Objects.equals(this.category4Id, categoryDTO.category4Id) &&
        Objects.equals(this.category4Name, categoryDTO.category4Name) &&
        Objects.equals(this.category5Id, categoryDTO.category5Id) &&
        Objects.equals(this.category5Name, categoryDTO.category5Name) &&
        Objects.equals(this.categoryId, categoryDTO.categoryId) &&
        Objects.equals(this.categoryLevel, categoryDTO.categoryLevel) &&
        Objects.equals(this.categoryName, categoryDTO.categoryName) &&
        Objects.equals(this.clientCat1Name, categoryDTO.clientCat1Name) &&
        Objects.equals(this.defaultDrf, categoryDTO.defaultDrf) &&
        Objects.equals(this.isitClass, categoryDTO.isitClass) &&
        Objects.equals(this.monthEndSortTitle, categoryDTO.monthEndSortTitle) &&
        Objects.equals(this.monthEndSortValue, categoryDTO.monthEndSortValue) &&
        Objects.equals(this.parentId, categoryDTO.parentId) &&
        Objects.equals(this.priceFactor, categoryDTO.priceFactor) &&
        Objects.equals(this.sortTitle, categoryDTO.sortTitle) &&
        Objects.equals(this.sortValue, categoryDTO.sortValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category0Id, category0Name, category1Id, category1Name, category2Id, category2Name, category3Id, category3Name, category4Id, category4Name, category5Id, category5Name, categoryId, categoryLevel, categoryName, clientCat1Name, defaultDrf, isitClass, monthEndSortTitle, monthEndSortValue, parentId, priceFactor, sortTitle, sortValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryDTO {\n");
    
    sb.append("    category0Id: ").append(toIndentedString(category0Id)).append("\n");
    sb.append("    category0Name: ").append(toIndentedString(category0Name)).append("\n");
    sb.append("    category1Id: ").append(toIndentedString(category1Id)).append("\n");
    sb.append("    category1Name: ").append(toIndentedString(category1Name)).append("\n");
    sb.append("    category2Id: ").append(toIndentedString(category2Id)).append("\n");
    sb.append("    category2Name: ").append(toIndentedString(category2Name)).append("\n");
    sb.append("    category3Id: ").append(toIndentedString(category3Id)).append("\n");
    sb.append("    category3Name: ").append(toIndentedString(category3Name)).append("\n");
    sb.append("    category4Id: ").append(toIndentedString(category4Id)).append("\n");
    sb.append("    category4Name: ").append(toIndentedString(category4Name)).append("\n");
    sb.append("    category5Id: ").append(toIndentedString(category5Id)).append("\n");
    sb.append("    category5Name: ").append(toIndentedString(category5Name)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    categoryLevel: ").append(toIndentedString(categoryLevel)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    clientCat1Name: ").append(toIndentedString(clientCat1Name)).append("\n");
    sb.append("    defaultDrf: ").append(toIndentedString(defaultDrf)).append("\n");
    sb.append("    isitClass: ").append(toIndentedString(isitClass)).append("\n");
    sb.append("    monthEndSortTitle: ").append(toIndentedString(monthEndSortTitle)).append("\n");
    sb.append("    monthEndSortValue: ").append(toIndentedString(monthEndSortValue)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    priceFactor: ").append(toIndentedString(priceFactor)).append("\n");
    sb.append("    sortTitle: ").append(toIndentedString(sortTitle)).append("\n");
    sb.append("    sortValue: ").append(toIndentedString(sortValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

