/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LRALInputDTO
 */

public class LRALInputDTO {
  @JsonProperty("omniAccountId")
  private Long omniAccountId = null;

  @JsonProperty("productLine")
  private String productLine = null;

  @JsonProperty("sourceAccountGroupIds")
  private List<Long> sourceAccountGroupIds = null;

  @JsonProperty("targetAccountGroupId")
  private Long targetAccountGroupId = null;

  @JsonProperty("userId")
  private Integer userId = null;

  public LRALInputDTO omniAccountId(Long omniAccountId) {
    this.omniAccountId = omniAccountId;
    return this;
  }

   /**
   * Get omniAccountId
   * @return omniAccountId
  **/
  @ApiModelProperty(value = "")
  public Long getOmniAccountId() {
    return omniAccountId;
  }

  public void setOmniAccountId(Long omniAccountId) {
    this.omniAccountId = omniAccountId;
  }

  public LRALInputDTO productLine(String productLine) {
    this.productLine = productLine;
    return this;
  }

   /**
   * Get productLine
   * @return productLine
  **/
  @ApiModelProperty(value = "")
  public String getProductLine() {
    return productLine;
  }

  public void setProductLine(String productLine) {
    this.productLine = productLine;
  }

  public LRALInputDTO sourceAccountGroupIds(List<Long> sourceAccountGroupIds) {
    this.sourceAccountGroupIds = sourceAccountGroupIds;
    return this;
  }

  public LRALInputDTO addSourceAccountGroupIdsItem(Long sourceAccountGroupIdsItem) {
    if (this.sourceAccountGroupIds == null) {
      this.sourceAccountGroupIds = new ArrayList<>();
    }
    this.sourceAccountGroupIds.add(sourceAccountGroupIdsItem);
    return this;
  }

   /**
   * Get sourceAccountGroupIds
   * @return sourceAccountGroupIds
  **/
  @ApiModelProperty(value = "")
  public List<Long> getSourceAccountGroupIds() {
    return sourceAccountGroupIds;
  }

  public void setSourceAccountGroupIds(List<Long> sourceAccountGroupIds) {
    this.sourceAccountGroupIds = sourceAccountGroupIds;
  }

  public LRALInputDTO targetAccountGroupId(Long targetAccountGroupId) {
    this.targetAccountGroupId = targetAccountGroupId;
    return this;
  }

   /**
   * Get targetAccountGroupId
   * @return targetAccountGroupId
  **/
  @ApiModelProperty(value = "")
  public Long getTargetAccountGroupId() {
    return targetAccountGroupId;
  }

  public void setTargetAccountGroupId(Long targetAccountGroupId) {
    this.targetAccountGroupId = targetAccountGroupId;
  }

  public LRALInputDTO userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LRALInputDTO lrALInputDTO = (LRALInputDTO) o;
    return Objects.equals(this.omniAccountId, lrALInputDTO.omniAccountId) &&
        Objects.equals(this.productLine, lrALInputDTO.productLine) &&
        Objects.equals(this.sourceAccountGroupIds, lrALInputDTO.sourceAccountGroupIds) &&
        Objects.equals(this.targetAccountGroupId, lrALInputDTO.targetAccountGroupId) &&
        Objects.equals(this.userId, lrALInputDTO.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(omniAccountId, productLine, sourceAccountGroupIds, targetAccountGroupId, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LRALInputDTO {\n");
    
    sb.append("    omniAccountId: ").append(toIndentedString(omniAccountId)).append("\n");
    sb.append("    productLine: ").append(toIndentedString(productLine)).append("\n");
    sb.append("    sourceAccountGroupIds: ").append(toIndentedString(sourceAccountGroupIds)).append("\n");
    sb.append("    targetAccountGroupId: ").append(toIndentedString(targetAccountGroupId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

