/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * PositionByVenueDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-23T11:29:17.054Z")
public class PositionByVenueDTO {
  @JsonProperty("avgRate")
  private Double avgRate = null;

  @JsonProperty("positionType")
  private String positionType = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("totalAmount")
  private Double totalAmount = null;

  @JsonProperty("totalDailyLoss")
  private Double totalDailyLoss = null;

  @JsonProperty("totalDailyPAndL")
  private Double totalDailyPAndL = null;

  @JsonProperty("totalDailyProfit")
  private Double totalDailyProfit = null;

  @JsonProperty("venue")
  private String venue = null;

  public PositionByVenueDTO avgRate(Double avgRate) {
    this.avgRate = avgRate;
    return this;
  }

   /**
   * Get avgRate
   * @return avgRate
  **/
  @ApiModelProperty(value = "")
  public Double getAvgRate() {
    return avgRate;
  }

  public void setAvgRate(Double avgRate) {
    this.avgRate = avgRate;
  }

  public PositionByVenueDTO positionType(String positionType) {
    this.positionType = positionType;
    return this;
  }

   /**
   * Get positionType
   * @return positionType
  **/
  @ApiModelProperty(value = "")
  public String getPositionType() {
    return positionType;
  }

  public void setPositionType(String positionType) {
    this.positionType = positionType;
  }

  public PositionByVenueDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public PositionByVenueDTO totalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Get totalAmount
   * @return totalAmount
  **/
  @ApiModelProperty(value = "")
  public Double getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }

  public PositionByVenueDTO totalDailyLoss(Double totalDailyLoss) {
    this.totalDailyLoss = totalDailyLoss;
    return this;
  }

   /**
   * Get totalDailyLoss
   * @return totalDailyLoss
  **/
  @ApiModelProperty(value = "")
  public Double getTotalDailyLoss() {
    return totalDailyLoss;
  }

  public void setTotalDailyLoss(Double totalDailyLoss) {
    this.totalDailyLoss = totalDailyLoss;
  }

  public PositionByVenueDTO totalDailyPAndL(Double totalDailyPAndL) {
    this.totalDailyPAndL = totalDailyPAndL;
    return this;
  }

   /**
   * Get totalDailyPAndL
   * @return totalDailyPAndL
  **/
  @ApiModelProperty(value = "")
  public Double getTotalDailyPAndL() {
    return totalDailyPAndL;
  }

  public void setTotalDailyPAndL(Double totalDailyPAndL) {
    this.totalDailyPAndL = totalDailyPAndL;
  }

  public PositionByVenueDTO totalDailyProfit(Double totalDailyProfit) {
    this.totalDailyProfit = totalDailyProfit;
    return this;
  }

   /**
   * Get totalDailyProfit
   * @return totalDailyProfit
  **/
  @ApiModelProperty(value = "")
  public Double getTotalDailyProfit() {
    return totalDailyProfit;
  }

  public void setTotalDailyProfit(Double totalDailyProfit) {
    this.totalDailyProfit = totalDailyProfit;
  }

  public PositionByVenueDTO venue(String venue) {
    this.venue = venue;
    return this;
  }

   /**
   * Get venue
   * @return venue
  **/
  @ApiModelProperty(value = "")
  public String getVenue() {
    return venue;
  }

  public void setVenue(String venue) {
    this.venue = venue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PositionByVenueDTO positionByVenueDTO = (PositionByVenueDTO) o;
    return Objects.equals(this.avgRate, positionByVenueDTO.avgRate) &&
        Objects.equals(this.positionType, positionByVenueDTO.positionType) &&
        Objects.equals(this.status, positionByVenueDTO.status) &&
        Objects.equals(this.totalAmount, positionByVenueDTO.totalAmount) &&
        Objects.equals(this.totalDailyLoss, positionByVenueDTO.totalDailyLoss) &&
        Objects.equals(this.totalDailyPAndL, positionByVenueDTO.totalDailyPAndL) &&
        Objects.equals(this.totalDailyProfit, positionByVenueDTO.totalDailyProfit) &&
        Objects.equals(this.venue, positionByVenueDTO.venue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avgRate, positionType, status, totalAmount, totalDailyLoss, totalDailyPAndL, totalDailyProfit, venue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PositionByVenueDTO {\n");
    
    sb.append("    avgRate: ").append(toIndentedString(avgRate)).append("\n");
    sb.append("    positionType: ").append(toIndentedString(positionType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    totalDailyLoss: ").append(toIndentedString(totalDailyLoss)).append("\n");
    sb.append("    totalDailyPAndL: ").append(toIndentedString(totalDailyPAndL)).append("\n");
    sb.append("    totalDailyProfit: ").append(toIndentedString(totalDailyProfit)).append("\n");
    sb.append("    venue: ").append(toIndentedString(venue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

