/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SGroupPositionOutDTO
 */

public class SGroupPositionOutDTO {
  @JsonProperty("avg")
  private PositionOutDTO avg = null;

  @JsonProperty("childrenGroupKeys")
  private List<String> childrenGroupKeys = null;

  @JsonProperty("endIndex")
  private Integer endIndex = null;

  @JsonProperty("groupLevel")
  private Integer groupLevel = null;

  @JsonProperty("groups")
  private List<SGroupPositionOutDTO> groups = null;

  @JsonProperty("key")
  private String key = null;

  @JsonProperty("max")
  private PositionOutDTO max = null;

  @JsonProperty("min")
  private PositionOutDTO min = null;

  @JsonProperty("startIndex")
  private Integer startIndex = null;

  @JsonProperty("sum")
  private PositionOutDTO sum = null;

  @JsonProperty("value")
  private Object value = null;

  public SGroupPositionOutDTO avg(PositionOutDTO avg) {
    this.avg = avg;
    return this;
  }

   /**
   * Get avg
   * @return avg
  **/
  @ApiModelProperty(value = "")
  public PositionOutDTO getAvg() {
    return avg;
  }

  public void setAvg(PositionOutDTO avg) {
    this.avg = avg;
  }

  public SGroupPositionOutDTO childrenGroupKeys(List<String> childrenGroupKeys) {
    this.childrenGroupKeys = childrenGroupKeys;
    return this;
  }

  public SGroupPositionOutDTO addChildrenGroupKeysItem(String childrenGroupKeysItem) {
    if (this.childrenGroupKeys == null) {
      this.childrenGroupKeys = new ArrayList<>();
    }
    this.childrenGroupKeys.add(childrenGroupKeysItem);
    return this;
  }

   /**
   * Get childrenGroupKeys
   * @return childrenGroupKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getChildrenGroupKeys() {
    return childrenGroupKeys;
  }

  public void setChildrenGroupKeys(List<String> childrenGroupKeys) {
    this.childrenGroupKeys = childrenGroupKeys;
  }

  public SGroupPositionOutDTO endIndex(Integer endIndex) {
    this.endIndex = endIndex;
    return this;
  }

   /**
   * Get endIndex
   * @return endIndex
  **/
  @ApiModelProperty(value = "")
  public Integer getEndIndex() {
    return endIndex;
  }

  public void setEndIndex(Integer endIndex) {
    this.endIndex = endIndex;
  }

  public SGroupPositionOutDTO groupLevel(Integer groupLevel) {
    this.groupLevel = groupLevel;
    return this;
  }

   /**
   * Get groupLevel
   * @return groupLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getGroupLevel() {
    return groupLevel;
  }

  public void setGroupLevel(Integer groupLevel) {
    this.groupLevel = groupLevel;
  }

  public SGroupPositionOutDTO groups(List<SGroupPositionOutDTO> groups) {
    this.groups = groups;
    return this;
  }

  public SGroupPositionOutDTO addGroupsItem(SGroupPositionOutDTO groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public List<SGroupPositionOutDTO> getGroups() {
    return groups;
  }

  public void setGroups(List<SGroupPositionOutDTO> groups) {
    this.groups = groups;
  }

  public SGroupPositionOutDTO key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public SGroupPositionOutDTO max(PositionOutDTO max) {
    this.max = max;
    return this;
  }

   /**
   * Get max
   * @return max
  **/
  @ApiModelProperty(value = "")
  public PositionOutDTO getMax() {
    return max;
  }

  public void setMax(PositionOutDTO max) {
    this.max = max;
  }

  public SGroupPositionOutDTO min(PositionOutDTO min) {
    this.min = min;
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @ApiModelProperty(value = "")
  public PositionOutDTO getMin() {
    return min;
  }

  public void setMin(PositionOutDTO min) {
    this.min = min;
  }

  public SGroupPositionOutDTO startIndex(Integer startIndex) {
    this.startIndex = startIndex;
    return this;
  }

   /**
   * Get startIndex
   * @return startIndex
  **/
  @ApiModelProperty(value = "")
  public Integer getStartIndex() {
    return startIndex;
  }

  public void setStartIndex(Integer startIndex) {
    this.startIndex = startIndex;
  }

  public SGroupPositionOutDTO sum(PositionOutDTO sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @ApiModelProperty(value = "")
  public PositionOutDTO getSum() {
    return sum;
  }

  public void setSum(PositionOutDTO sum) {
    this.sum = sum;
  }

  public SGroupPositionOutDTO value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SGroupPositionOutDTO sgroupPositionOutDTO = (SGroupPositionOutDTO) o;
    return Objects.equals(this.avg, sgroupPositionOutDTO.avg) &&
        Objects.equals(this.childrenGroupKeys, sgroupPositionOutDTO.childrenGroupKeys) &&
        Objects.equals(this.endIndex, sgroupPositionOutDTO.endIndex) &&
        Objects.equals(this.groupLevel, sgroupPositionOutDTO.groupLevel) &&
        Objects.equals(this.groups, sgroupPositionOutDTO.groups) &&
        Objects.equals(this.key, sgroupPositionOutDTO.key) &&
        Objects.equals(this.max, sgroupPositionOutDTO.max) &&
        Objects.equals(this.min, sgroupPositionOutDTO.min) &&
        Objects.equals(this.startIndex, sgroupPositionOutDTO.startIndex) &&
        Objects.equals(this.sum, sgroupPositionOutDTO.sum) &&
        Objects.equals(this.value, sgroupPositionOutDTO.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avg, childrenGroupKeys, endIndex, groupLevel, groups, key, max, min, startIndex, sum, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SGroupPositionOutDTO {\n");
    
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("    childrenGroupKeys: ").append(toIndentedString(childrenGroupKeys)).append("\n");
    sb.append("    endIndex: ").append(toIndentedString(endIndex)).append("\n");
    sb.append("    groupLevel: ").append(toIndentedString(groupLevel)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

