/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.intellecteu.onesource.integration.services.client.spire.dto.NQueryResponseTradeOutDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SResponseNQueryResponseTradeOutDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-02-20T15:00:33.025Z")
public class SResponseNQueryResponseTradeOutDTO {
  @JsonProperty("data")
  private NQueryResponseTradeOutDTO data = null;

  @JsonProperty("errCode")
  private String errCode = null;

  @JsonProperty("error")
  private Boolean error = null;

  @JsonProperty("message")
  private String message = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ERROR("ERROR"),
    
    SUCCESS("SUCCESS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("success")
  private Boolean success = null;

  public SResponseNQueryResponseTradeOutDTO data(NQueryResponseTradeOutDTO data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public NQueryResponseTradeOutDTO getData() {
    return data;
  }

  public void setData(NQueryResponseTradeOutDTO data) {
    this.data = data;
  }

  public SResponseNQueryResponseTradeOutDTO errCode(String errCode) {
    this.errCode = errCode;
    return this;
  }

   /**
   * Get errCode
   * @return errCode
  **/
  @ApiModelProperty(value = "")
  public String getErrCode() {
    return errCode;
  }

  public void setErrCode(String errCode) {
    this.errCode = errCode;
  }

  public SResponseNQueryResponseTradeOutDTO error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public SResponseNQueryResponseTradeOutDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public SResponseNQueryResponseTradeOutDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SResponseNQueryResponseTradeOutDTO success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @ApiModelProperty(value = "")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SResponseNQueryResponseTradeOutDTO sresponseNQueryResponseTradeOutDTO = (SResponseNQueryResponseTradeOutDTO) o;
    return Objects.equals(this.data, sresponseNQueryResponseTradeOutDTO.data) &&
        Objects.equals(this.errCode, sresponseNQueryResponseTradeOutDTO.errCode) &&
        Objects.equals(this.error, sresponseNQueryResponseTradeOutDTO.error) &&
        Objects.equals(this.message, sresponseNQueryResponseTradeOutDTO.message) &&
        Objects.equals(this.status, sresponseNQueryResponseTradeOutDTO.status) &&
        Objects.equals(this.success, sresponseNQueryResponseTradeOutDTO.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, errCode, error, message, status, success);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SResponseNQueryResponseTradeOutDTO {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    errCode: ").append(toIndentedString(errCode)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

