/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * SwiftMessageStatusResponseDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-23T11:29:17.054Z")
public class SwiftMessageStatusResponseDTO {
  @JsonProperty("SWIFTInboxMessageId")
  private String swIFTInboxMessageId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("statusCd")
  private Integer statusCd = null;

  @JsonProperty("statusDesc")
  private String statusDesc = null;

  public SwiftMessageStatusResponseDTO swIFTInboxMessageId(String swIFTInboxMessageId) {
    this.swIFTInboxMessageId = swIFTInboxMessageId;
    return this;
  }

   /**
   * Get swIFTInboxMessageId
   * @return swIFTInboxMessageId
  **/
  @ApiModelProperty(value = "")
  public String getSwIFTInboxMessageId() {
    return swIFTInboxMessageId;
  }

  public void setSwIFTInboxMessageId(String swIFTInboxMessageId) {
    this.swIFTInboxMessageId = swIFTInboxMessageId;
  }

  public SwiftMessageStatusResponseDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SwiftMessageStatusResponseDTO statusCd(Integer statusCd) {
    this.statusCd = statusCd;
    return this;
  }

   /**
   * Get statusCd
   * @return statusCd
  **/
  @ApiModelProperty(value = "")
  public Integer getStatusCd() {
    return statusCd;
  }

  public void setStatusCd(Integer statusCd) {
    this.statusCd = statusCd;
  }

  public SwiftMessageStatusResponseDTO statusDesc(String statusDesc) {
    this.statusDesc = statusDesc;
    return this;
  }

   /**
   * Get statusDesc
   * @return statusDesc
  **/
  @ApiModelProperty(value = "")
  public String getStatusDesc() {
    return statusDesc;
  }

  public void setStatusDesc(String statusDesc) {
    this.statusDesc = statusDesc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SwiftMessageStatusResponseDTO swiftMessageStatusResponseDTO = (SwiftMessageStatusResponseDTO) o;
    return Objects.equals(this.swIFTInboxMessageId, swiftMessageStatusResponseDTO.swIFTInboxMessageId) &&
        Objects.equals(this.status, swiftMessageStatusResponseDTO.status) &&
        Objects.equals(this.statusCd, swiftMessageStatusResponseDTO.statusCd) &&
        Objects.equals(this.statusDesc, swiftMessageStatusResponseDTO.statusDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(swIFTInboxMessageId, status, statusCd, statusDesc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SwiftMessageStatusResponseDTO {\n");
    
    sb.append("    swIFTInboxMessageId: ").append(toIndentedString(swIFTInboxMessageId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusCd: ").append(toIndentedString(statusCd)).append("\n");
    sb.append("    statusDesc: ").append(toIndentedString(statusDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

