/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * TradeBySecurityDTO
 */

public class TradeBySecurityDTO {
  @JsonProperty("avgRate")
  private Double avgRate = null;

  @JsonProperty("cusip")
  private String cusip = null;

  @JsonProperty("isin")
  private String isin = null;

  @JsonProperty("loanStatus")
  private String loanStatus = null;

  @JsonProperty("sedol")
  private String sedol = null;

  @JsonProperty("totalActivityLoss")
  private Double totalActivityLoss = null;

  @JsonProperty("totalActivityPAndL")
  private Double totalActivityPAndL = null;

  @JsonProperty("totalActivityProfit")
  private Double totalActivityProfit = null;

  @JsonProperty("totalAmount")
  private Double totalAmount = null;

  @JsonProperty("tradeType")
  private String tradeType = null;

  public TradeBySecurityDTO avgRate(Double avgRate) {
    this.avgRate = avgRate;
    return this;
  }

   /**
   * Get avgRate
   * @return avgRate
  **/
  @ApiModelProperty(value = "")
  public Double getAvgRate() {
    return avgRate;
  }

  public void setAvgRate(Double avgRate) {
    this.avgRate = avgRate;
  }

  public TradeBySecurityDTO cusip(String cusip) {
    this.cusip = cusip;
    return this;
  }

   /**
   * Get cusip
   * @return cusip
  **/
  @ApiModelProperty(value = "")
  public String getCusip() {
    return cusip;
  }

  public void setCusip(String cusip) {
    this.cusip = cusip;
  }

  public TradeBySecurityDTO isin(String isin) {
    this.isin = isin;
    return this;
  }

   /**
   * Get isin
   * @return isin
  **/
  @ApiModelProperty(value = "")
  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public TradeBySecurityDTO loanStatus(String loanStatus) {
    this.loanStatus = loanStatus;
    return this;
  }

   /**
   * Get loanStatus
   * @return loanStatus
  **/
  @ApiModelProperty(value = "")
  public String getLoanStatus() {
    return loanStatus;
  }

  public void setLoanStatus(String loanStatus) {
    this.loanStatus = loanStatus;
  }

  public TradeBySecurityDTO sedol(String sedol) {
    this.sedol = sedol;
    return this;
  }

   /**
   * Get sedol
   * @return sedol
  **/
  @ApiModelProperty(value = "")
  public String getSedol() {
    return sedol;
  }

  public void setSedol(String sedol) {
    this.sedol = sedol;
  }

  public TradeBySecurityDTO totalActivityLoss(Double totalActivityLoss) {
    this.totalActivityLoss = totalActivityLoss;
    return this;
  }

   /**
   * Get totalActivityLoss
   * @return totalActivityLoss
  **/
  @ApiModelProperty(value = "")
  public Double getTotalActivityLoss() {
    return totalActivityLoss;
  }

  public void setTotalActivityLoss(Double totalActivityLoss) {
    this.totalActivityLoss = totalActivityLoss;
  }

  public TradeBySecurityDTO totalActivityPAndL(Double totalActivityPAndL) {
    this.totalActivityPAndL = totalActivityPAndL;
    return this;
  }

   /**
   * Get totalActivityPAndL
   * @return totalActivityPAndL
  **/
  @ApiModelProperty(value = "")
  public Double getTotalActivityPAndL() {
    return totalActivityPAndL;
  }

  public void setTotalActivityPAndL(Double totalActivityPAndL) {
    this.totalActivityPAndL = totalActivityPAndL;
  }

  public TradeBySecurityDTO totalActivityProfit(Double totalActivityProfit) {
    this.totalActivityProfit = totalActivityProfit;
    return this;
  }

   /**
   * Get totalActivityProfit
   * @return totalActivityProfit
  **/
  @ApiModelProperty(value = "")
  public Double getTotalActivityProfit() {
    return totalActivityProfit;
  }

  public void setTotalActivityProfit(Double totalActivityProfit) {
    this.totalActivityProfit = totalActivityProfit;
  }

  public TradeBySecurityDTO totalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
    return this;
  }

   /**
   * Get totalAmount
   * @return totalAmount
  **/
  @ApiModelProperty(value = "")
  public Double getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }

  public TradeBySecurityDTO tradeType(String tradeType) {
    this.tradeType = tradeType;
    return this;
  }

   /**
   * Get tradeType
   * @return tradeType
  **/
  @ApiModelProperty(value = "")
  public String getTradeType() {
    return tradeType;
  }

  public void setTradeType(String tradeType) {
    this.tradeType = tradeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeBySecurityDTO tradeBySecurityDTO = (TradeBySecurityDTO) o;
    return Objects.equals(this.avgRate, tradeBySecurityDTO.avgRate) &&
        Objects.equals(this.cusip, tradeBySecurityDTO.cusip) &&
        Objects.equals(this.isin, tradeBySecurityDTO.isin) &&
        Objects.equals(this.loanStatus, tradeBySecurityDTO.loanStatus) &&
        Objects.equals(this.sedol, tradeBySecurityDTO.sedol) &&
        Objects.equals(this.totalActivityLoss, tradeBySecurityDTO.totalActivityLoss) &&
        Objects.equals(this.totalActivityPAndL, tradeBySecurityDTO.totalActivityPAndL) &&
        Objects.equals(this.totalActivityProfit, tradeBySecurityDTO.totalActivityProfit) &&
        Objects.equals(this.totalAmount, tradeBySecurityDTO.totalAmount) &&
        Objects.equals(this.tradeType, tradeBySecurityDTO.tradeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avgRate, cusip, isin, loanStatus, sedol, totalActivityLoss, totalActivityPAndL, totalActivityProfit, totalAmount, tradeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeBySecurityDTO {\n");
    
    sb.append("    avgRate: ").append(toIndentedString(avgRate)).append("\n");
    sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    loanStatus: ").append(toIndentedString(loanStatus)).append("\n");
    sb.append("    sedol: ").append(toIndentedString(sedol)).append("\n");
    sb.append("    totalActivityLoss: ").append(toIndentedString(totalActivityLoss)).append("\n");
    sb.append("    totalActivityPAndL: ").append(toIndentedString(totalActivityPAndL)).append("\n");
    sb.append("    totalActivityProfit: ").append(toIndentedString(totalActivityProfit)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    tradeType: ").append(toIndentedString(tradeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

