/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * TradingdeskDTO
 */

public class TradingdeskDTO {
  @JsonProperty("calendarId")
  private Integer calendarId = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("tradingDeskId")
  private Integer tradingDeskId = null;

  @JsonProperty("tradingDeskName")
  private String tradingDeskName = null;

  public TradingdeskDTO calendarId(Integer calendarId) {
    this.calendarId = calendarId;
    return this;
  }

   /**
   * Get calendarId
   * @return calendarId
  **/
  @ApiModelProperty(value = "")
  public Integer getCalendarId() {
    return calendarId;
  }

  public void setCalendarId(Integer calendarId) {
    this.calendarId = calendarId;
  }

  public TradingdeskDTO timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public TradingdeskDTO tradingDeskId(Integer tradingDeskId) {
    this.tradingDeskId = tradingDeskId;
    return this;
  }

   /**
   * Get tradingDeskId
   * @return tradingDeskId
  **/
  @ApiModelProperty(value = "")
  public Integer getTradingDeskId() {
    return tradingDeskId;
  }

  public void setTradingDeskId(Integer tradingDeskId) {
    this.tradingDeskId = tradingDeskId;
  }

  public TradingdeskDTO tradingDeskName(String tradingDeskName) {
    this.tradingDeskName = tradingDeskName;
    return this;
  }

   /**
   * Get tradingDeskName
   * @return tradingDeskName
  **/
  @ApiModelProperty(value = "")
  public String getTradingDeskName() {
    return tradingDeskName;
  }

  public void setTradingDeskName(String tradingDeskName) {
    this.tradingDeskName = tradingDeskName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradingdeskDTO tradingdeskDTO = (TradingdeskDTO) o;
    return Objects.equals(this.calendarId, tradingdeskDTO.calendarId) &&
        Objects.equals(this.timezone, tradingdeskDTO.timezone) &&
        Objects.equals(this.tradingDeskId, tradingdeskDTO.tradingDeskId) &&
        Objects.equals(this.tradingDeskName, tradingdeskDTO.tradingDeskName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calendarId, timezone, tradingDeskId, tradingDeskName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradingdeskDTO {\n");
    
    sb.append("    calendarId: ").append(toIndentedString(calendarId)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    tradingDeskId: ").append(toIndentedString(tradingDeskId)).append("\n");
    sb.append("    tradingDeskName: ").append(toIndentedString(tradingDeskName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

