/*
 * Spire-Trade-Service
 * Spire-Trade-REST-API
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UserDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-23T11:29:17.054Z")
public class UserDTO {
  @JsonProperty("accountId")
  private Long accountId = null;

  @JsonProperty("accountNo")
  private String accountNo = null;

  @JsonProperty("companyId")
  private Long companyId = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("extUserName")
  private String extUserName = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("homePageId")
  private Long homePageId = null;

  @JsonProperty("hrId")
  private String hrId = null;

  @JsonProperty("inactive")
  private Boolean inactive = null;

  @JsonProperty("isExecuteTrader")
  private Integer isExecuteTrader = null;

  @JsonProperty("isRecommendTrader")
  private Integer isRecommendTrader = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("profileId")
  private Long profileId = null;

  @JsonProperty("shortName")
  private String shortName = null;

  @JsonProperty("supervisorId")
  private Long supervisorId = null;

  @JsonProperty("tradingDeskId")
  private Integer tradingDeskId = null;

  @JsonProperty("userCategory")
  private String userCategory = null;

  @JsonProperty("userGroups")
  private List<String> userGroups = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("userName")
  private String userName = null;

  @JsonProperty("userType")
  private String userType = null;

  public UserDTO accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public UserDTO accountNo(String accountNo) {
    this.accountNo = accountNo;
    return this;
  }

   /**
   * Get accountNo
   * @return accountNo
  **/
  @ApiModelProperty(value = "")
  public String getAccountNo() {
    return accountNo;
  }

  public void setAccountNo(String accountNo) {
    this.accountNo = accountNo;
  }

  public UserDTO companyId(Long companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @ApiModelProperty(value = "")
  public Long getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Long companyId) {
    this.companyId = companyId;
  }

  public UserDTO email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserDTO extUserName(String extUserName) {
    this.extUserName = extUserName;
    return this;
  }

   /**
   * Get extUserName
   * @return extUserName
  **/
  @ApiModelProperty(value = "")
  public String getExtUserName() {
    return extUserName;
  }

  public void setExtUserName(String extUserName) {
    this.extUserName = extUserName;
  }

  public UserDTO firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserDTO homePageId(Long homePageId) {
    this.homePageId = homePageId;
    return this;
  }

   /**
   * Get homePageId
   * @return homePageId
  **/
  @ApiModelProperty(value = "")
  public Long getHomePageId() {
    return homePageId;
  }

  public void setHomePageId(Long homePageId) {
    this.homePageId = homePageId;
  }

  public UserDTO hrId(String hrId) {
    this.hrId = hrId;
    return this;
  }

   /**
   * Get hrId
   * @return hrId
  **/
  @ApiModelProperty(value = "")
  public String getHrId() {
    return hrId;
  }

  public void setHrId(String hrId) {
    this.hrId = hrId;
  }

  public UserDTO inactive(Boolean inactive) {
    this.inactive = inactive;
    return this;
  }

   /**
   * Get inactive
   * @return inactive
  **/
  @ApiModelProperty(value = "")
  public Boolean isInactive() {
    return inactive;
  }

  public void setInactive(Boolean inactive) {
    this.inactive = inactive;
  }

  public UserDTO isExecuteTrader(Integer isExecuteTrader) {
    this.isExecuteTrader = isExecuteTrader;
    return this;
  }

   /**
   * Get isExecuteTrader
   * @return isExecuteTrader
  **/
  @ApiModelProperty(value = "")
  public Integer getIsExecuteTrader() {
    return isExecuteTrader;
  }

  public void setIsExecuteTrader(Integer isExecuteTrader) {
    this.isExecuteTrader = isExecuteTrader;
  }

  public UserDTO isRecommendTrader(Integer isRecommendTrader) {
    this.isRecommendTrader = isRecommendTrader;
    return this;
  }

   /**
   * Get isRecommendTrader
   * @return isRecommendTrader
  **/
  @ApiModelProperty(value = "")
  public Integer getIsRecommendTrader() {
    return isRecommendTrader;
  }

  public void setIsRecommendTrader(Integer isRecommendTrader) {
    this.isRecommendTrader = isRecommendTrader;
  }

  public UserDTO lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserDTO profileId(Long profileId) {
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @ApiModelProperty(value = "")
  public Long getProfileId() {
    return profileId;
  }

  public void setProfileId(Long profileId) {
    this.profileId = profileId;
  }

  public UserDTO shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @ApiModelProperty(value = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public UserDTO supervisorId(Long supervisorId) {
    this.supervisorId = supervisorId;
    return this;
  }

   /**
   * Get supervisorId
   * @return supervisorId
  **/
  @ApiModelProperty(value = "")
  public Long getSupervisorId() {
    return supervisorId;
  }

  public void setSupervisorId(Long supervisorId) {
    this.supervisorId = supervisorId;
  }

  public UserDTO tradingDeskId(Integer tradingDeskId) {
    this.tradingDeskId = tradingDeskId;
    return this;
  }

   /**
   * Get tradingDeskId
   * @return tradingDeskId
  **/
  @ApiModelProperty(value = "")
  public Integer getTradingDeskId() {
    return tradingDeskId;
  }

  public void setTradingDeskId(Integer tradingDeskId) {
    this.tradingDeskId = tradingDeskId;
  }

  public UserDTO userCategory(String userCategory) {
    this.userCategory = userCategory;
    return this;
  }

   /**
   * Get userCategory
   * @return userCategory
  **/
  @ApiModelProperty(value = "")
  public String getUserCategory() {
    return userCategory;
  }

  public void setUserCategory(String userCategory) {
    this.userCategory = userCategory;
  }

  public UserDTO userGroups(List<String> userGroups) {
    this.userGroups = userGroups;
    return this;
  }

  public UserDTO addUserGroupsItem(String userGroupsItem) {
    if (this.userGroups == null) {
      this.userGroups = new ArrayList<>();
    }
    this.userGroups.add(userGroupsItem);
    return this;
  }

   /**
   * Get userGroups
   * @return userGroups
  **/
  @ApiModelProperty(value = "")
  public List<String> getUserGroups() {
    return userGroups;
  }

  public void setUserGroups(List<String> userGroups) {
    this.userGroups = userGroups;
  }

  public UserDTO userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public UserDTO userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public UserDTO userType(String userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @ApiModelProperty(value = "")
  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDTO userDTO = (UserDTO) o;
    return Objects.equals(this.accountId, userDTO.accountId) &&
        Objects.equals(this.accountNo, userDTO.accountNo) &&
        Objects.equals(this.companyId, userDTO.companyId) &&
        Objects.equals(this.email, userDTO.email) &&
        Objects.equals(this.extUserName, userDTO.extUserName) &&
        Objects.equals(this.firstName, userDTO.firstName) &&
        Objects.equals(this.homePageId, userDTO.homePageId) &&
        Objects.equals(this.hrId, userDTO.hrId) &&
        Objects.equals(this.inactive, userDTO.inactive) &&
        Objects.equals(this.isExecuteTrader, userDTO.isExecuteTrader) &&
        Objects.equals(this.isRecommendTrader, userDTO.isRecommendTrader) &&
        Objects.equals(this.lastName, userDTO.lastName) &&
        Objects.equals(this.profileId, userDTO.profileId) &&
        Objects.equals(this.shortName, userDTO.shortName) &&
        Objects.equals(this.supervisorId, userDTO.supervisorId) &&
        Objects.equals(this.tradingDeskId, userDTO.tradingDeskId) &&
        Objects.equals(this.userCategory, userDTO.userCategory) &&
        Objects.equals(this.userGroups, userDTO.userGroups) &&
        Objects.equals(this.userId, userDTO.userId) &&
        Objects.equals(this.userName, userDTO.userName) &&
        Objects.equals(this.userType, userDTO.userType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountNo, companyId, email, extUserName, firstName, homePageId, hrId, inactive, isExecuteTrader, isRecommendTrader, lastName, profileId, shortName, supervisorId, tradingDeskId, userCategory, userGroups, userId, userName, userType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDTO {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountNo: ").append(toIndentedString(accountNo)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    extUserName: ").append(toIndentedString(extUserName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    homePageId: ").append(toIndentedString(homePageId)).append("\n");
    sb.append("    hrId: ").append(toIndentedString(hrId)).append("\n");
    sb.append("    inactive: ").append(toIndentedString(inactive)).append("\n");
    sb.append("    isExecuteTrader: ").append(toIndentedString(isExecuteTrader)).append("\n");
    sb.append("    isRecommendTrader: ").append(toIndentedString(isRecommendTrader)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    supervisorId: ").append(toIndentedString(supervisorId)).append("\n");
    sb.append("    tradingDeskId: ").append(toIndentedString(tradingDeskId)).append("\n");
    sb.append("    userCategory: ").append(toIndentedString(userCategory)).append("\n");
    sb.append("    userGroups: ").append(toIndentedString(userGroups)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

