camel:
  timer: ${CAMEL_TIMER_LOCAL:9000}
  newPositionTimer: ${CAMEL_TIMER_LOCAL:9000}
  positionTimer: ${CAMEL_TIMER_LOCAL:9000}
  partyTimer: ${PARTY_TIMER:0+0+6+*+*+?}
  timestamp: ${CAMEL_TIMESTAMP_LOCAL:2023-06-25T09:51:16.111Z}
  route:
    autostart: ${CAMEL_AUTOSTART_LOCAL:true}

spring:
  datasource:
    driverClassName: ${DB_DRIVER_LOCAL:org.postgresql.Driver}
    url: ${DB_URL_LOCAL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME_LOCAL:postgres}
    password: ${DB_PASSWORD_LOCAL:postgres}
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA_LOCAL:postgres}
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration, classpath:local/db/migration
    baseline-on-migrate: true
    url: ${DB_URL_LOCAL:jdbc:postgresql://localhost:5432/postgres}
    user: ${DB_USERNAME_LOCAL:postgres}
    password: ${DB_PASSWORD_LOCAL:postgres}
    schemas: ${DB_SCHEMA_LOCAL:postgres}
    enabled: true
    default-schema: ${DB_SCHEMA_LOCAL:postgres}

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX

logging:
  level:
    com:
      intellecteu:
        onesource:
          integration:
            config: INFO
            mapper: DEBUG
            dto: DEBUG
            routes: DEBUG
            services: DEBUG
            utils: DEBUG
    org:
      apache:
        kafka: WARN
      springframework:
        web:
          client:
            RestTemplate: INFO
    root: INFO

onesource:
  baseEndpoint: ${1SOURCE_ENDPOINT_LOCAL:http://localhost:8081}
  version:
  auth:
    server-url: ${1SOURCE_AUTH_URL_LOCAL:http://localhost:8088}
    realm: ${1SOURCE_AUTH_REALM_LOCAL:1source-keycloak}
    public-client: true
    resource: ${1SOURCE_AUTH_CLIENT_ID_LOCAL:1source-integration}
    principal-attribute: ${1SOURCE_AUTH_PRINCIPAL_ATTRIBUTE_LOCAL:preferred_username}
    username: ${1SOURCE_AUTH_USER_NAME_LOCAL:test-user}
    password: ${1SOURCE_AUTH_USER_PASSWORD_LOCAL:12345}
    credentials:
      secret: ${1SOURCE_AUTH_CLIENT_SECRET_LOCAL:secret}

spire:
  lenderEndpoint: ${SPIRE_LENDER_ENDPOINT_LOCAL:http://localhost:8083/lender}
  borrowerEndpoint: ${SPIRE_BORROWER_ENDPOINT_LOCAL:http://localhost:8083/borrower}
  username: ${SPIRE_LENDER_USERNAME_LOCAL:test-user}
  password: ${SPIRE_LENDER_PASSWORD_LOCAL:12345}

cloudevents:
  specversion: ${CLOUD_EVENTS_SPEC_VERSION_LOCAL:1.0}

integration-toolkit:
  route:
    rerate:
      enable: true
    contract-initiation-trade-started:
      enable: true
    contract-initiation-without-trade-route:
      enable: true
  uri: ${INTEGRATION_TOOLKIT_URI_LOCAL:http://integration.toolkit}

notification:
  enable: ${NOTIFICATION_ENABLE_LOCAL:false}
  timer: ${NOTIFICATION_TIMER_LOCAL:10000}
  spire:
    bootstrap-server: ${SPIRE_BOOTSTRAP_SERVER_LOCAL:localhost:9092}
    topic: ${NOTIFICATION_SPIRE_TOPIC_LOCAL:TEST.TOPIC}
    auth:
      key: ${NOTIFICATION_SPIRE_KEY_LOCAL:test}
      secret: ${NOTIFICATION_SPIRE_SECRET_LOCAL:test}