camel:
  route:
    autostart: false

spring:
  flyway:
    enabled: false

logging:
  level:
    com:
      intellecteu:
        onesource:
          integration: DEBUG
    root: INFO

onesource:
  baseEndpoint: http://localhost:8081
  version:
  auth:
    server-url: http://localhost:8088
    realm: 1source-keycloak
    public-client: true
    resource: 1source-integration
    principal-attribute: preferred_username
    username: test-user
    password: 12345
    credentials:
      secret: secret

spire:
  lenderEndpoint: ${SPIRE_LENDER_ENDPOINT_DEV:http://localhost:8083}
  borrowerEndpoint: ${SPIRE_LENDER_ENDPOINT_DEV:http://localhost:8083}
  username: ${SPIRE_LENDER_USERNAME_DEV:TestUser}
  password: ${SPIRE_LENDER_PASSWORD_DEV:Password}
