camel:
  timer: ${CAMEL_TIMER:100000}
  newPositionTimer: ${CAMEL_TIMER:600000}
  positionTimer: ${CAMEL_TIMER:600000}
  newBackOfficeTradeEventTimer: ${CAMEL_TIMER:600000}
  partyTimer: ${PARTY_TIMER:0+0+6+*+*+?}
  timestamp: ${CAMEL_TIMESTAMP:2023-06-25T09:51:16.111Z}
  route:
    autostart: ${CAMEL_AUTOSTART:true}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://1source-postgres:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:postgres}
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${DB_URL:jdbc:postgresql://1source-postgres:5432/postgres}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:postgres}
    enabled: true
    default-schema: ${DB_SCHEMA:postgres}

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSX

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${onesource.auth.api.server-url}/realms/${onesource.auth.api.realm}
          jwk-set-uri: ${onesource.auth.api.server-url}/realms/${onesource.auth.api.realm}/protocol/openid-connect/certs

logging:
  level:
    com:
      intellecteu:
        onesource:
          integration: DEBUG
    org:
      apache:
        kafka: WARN
      springframework:
        web:
          client:
            RestTemplate: INFO
    root: INFO

onesource:
  baseEndpoint: ${1SOURCE_ENDPOINT}
  version: ${1SOURCE_VERSION:/v1/}
  auth:
    api:
      server-url: ${1SOURCE_AUTH_API_URL}
      realm: ${1SOURCE_AUTH_API_REALM}
      resource: ${1SOURCE_AUTH_API_CLIENT_ID}
    server-url: ${1SOURCE_AUTH_URL}
    realm: ${1SOURCE_AUTH_REALM}
    public-client: true
    resource: ${1SOURCE_AUTH_CLIENT_ID}
    principal-attribute: ${1SOURCE_AUTH_PRINCIPAL_ATTRIBUTE:preferred_username}
    username: ${1SOURCE_AUTH_USER_NAME}
    password: ${1SOURCE_AUTH_USER_PASSWORD}
    credentials:
      secret: ${1SOURCE_AUTH_CLIENT_SECRET}

spire:
  baseEndpoint: ${SPIRE_BASE_ENDPOINT}
  lenderEndpoint: ${SPIRE_LENDER_ENDPOINT}
  borrowerEndpoint: ${SPIRE_BORROWER_ENDPOINT}
  username: ${SPIRE_LENDER_USERNAME}
  password: ${SPIRE_LENDER_PASSWORD}

cloudevents:
  specversion: ${CLOUD_EVENTS_SPEC_VERSION:1.0}

integration-toolkit:
  starting-trade-event-datetime: ${CAMEL_TIMESTAMP:2023-06-25T09:51:16.111Z}
  route:
    rerate:
      enable: ${RERATE_ROUTE:true}
    contract-initiation-trade-started:
      enable: ${CI_WITH_TRADE_ROUTE:true}
    contract-initiation-without-trade-route:
      enable: ${CI_WITHOUT_TRADE_ROUTE:true}
  uri: ${INTEGRATION_TOOLKIT_URI:http://integration.toolkit}

notification:
  enable: ${NOTIFICATION_ENABLE:false}
  timer: ${NOTIFICATION_TIMER:100000}
  spire:
    bootstrap-server: ${SPIRE_BOOTSTRAP_SERVER:localhost:9092}
    topic: ${NOTIFICATION_SPIRE_TOPIC:TEST.TOPIC}
    auth:
      key: ${NOTIFICATION_SPIRE_KEY:empty}
      secret: ${NOTIFICATION_SPIRE_SECRET:empty}