/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intellecteu.onesource.integration.services.client.onesource.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.util.Objects;
/**
 * BuyinCompleteRequestDTO
 */



public class BuyinCompleteRequestDTO {
  @JsonProperty("quantity")
  private Integer quantity = null;

  @JsonProperty("buyinDate")
  private LocalDate buyinDate = null;

  @JsonProperty("price")
  private PriceDTO price = null;

  public BuyinCompleteRequestDTO quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public BuyinCompleteRequestDTO buyinDate(LocalDate buyinDate) {
    this.buyinDate = buyinDate;
    return this;
  }

   /**
   * Get buyinDate
   * @return buyinDate
  **/
  @Schema(description = "")
  public LocalDate getBuyinDate() {
    return buyinDate;
  }

  public void setBuyinDate(LocalDate buyinDate) {
    this.buyinDate = buyinDate;
  }

  public BuyinCompleteRequestDTO price(PriceDTO price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public PriceDTO getPrice() {
    return price;
  }

  public void setPrice(PriceDTO price) {
    this.price = price;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyinCompleteRequestDTO buyinCompleteRequest = (BuyinCompleteRequestDTO) o;
    return Objects.equals(this.quantity, buyinCompleteRequest.quantity) &&
        Objects.equals(this.buyinDate, buyinCompleteRequest.buyinDate) &&
        Objects.equals(this.price, buyinCompleteRequest.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, buyinDate, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyinCompleteRequestDTO {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    buyinDate: ").append(toIndentedString(buyinDate)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
