/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intellecteu.onesource.integration.services.client.onesource.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
/**
 * PartySettlementInstructionDTO
 */



public class PartySettlementInstructionDTO {
  @JsonProperty("partyRole")
  private PartyRoleDTO partyRole = null;

  @JsonProperty("settlementStatus")
  private SettlementStatusDTO settlementStatus = null;

  @JsonProperty("internalAcctCd")
  private String internalAcctCd = null;

  @JsonProperty("instruction")
  private SettlementInstructionDTO instruction = null;

  public PartySettlementInstructionDTO partyRole(PartyRoleDTO partyRole) {
    this.partyRole = partyRole;
    return this;
  }

   /**
   * Get partyRole
   * @return partyRole
  **/
  @Schema(description = "")
  public PartyRoleDTO getPartyRole() {
    return partyRole;
  }

  public void setPartyRole(PartyRoleDTO partyRole) {
    this.partyRole = partyRole;
  }

  public PartySettlementInstructionDTO settlementStatus(SettlementStatusDTO settlementStatus) {
    this.settlementStatus = settlementStatus;
    return this;
  }

   /**
   * Get settlementStatus
   * @return settlementStatus
  **/
  @Schema(description = "")
  public SettlementStatusDTO getSettlementStatus() {
    return settlementStatus;
  }

  public void setSettlementStatus(SettlementStatusDTO settlementStatus) {
    this.settlementStatus = settlementStatus;
  }

  public PartySettlementInstructionDTO internalAcctCd(String internalAcctCd) {
    this.internalAcctCd = internalAcctCd;
    return this;
  }

   /**
   * Get internalAcctCd
   * @return internalAcctCd
  **/
  @Schema(description = "")
  public String getInternalAcctCd() {
    return internalAcctCd;
  }

  public void setInternalAcctCd(String internalAcctCd) {
    this.internalAcctCd = internalAcctCd;
  }

  public PartySettlementInstructionDTO instruction(SettlementInstructionDTO instruction) {
    this.instruction = instruction;
    return this;
  }

   /**
   * Get instruction
   * @return instruction
  **/
  @Schema(description = "")
  public SettlementInstructionDTO getInstruction() {
    return instruction;
  }

  public void setInstruction(SettlementInstructionDTO instruction) {
    this.instruction = instruction;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartySettlementInstructionDTO partySettlementInstruction = (PartySettlementInstructionDTO) o;
    return Objects.equals(this.partyRole, partySettlementInstruction.partyRole) &&
        Objects.equals(this.settlementStatus, partySettlementInstruction.settlementStatus) &&
        Objects.equals(this.internalAcctCd, partySettlementInstruction.internalAcctCd) &&
        Objects.equals(this.instruction, partySettlementInstruction.instruction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyRole, settlementStatus, internalAcctCd, instruction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartySettlementInstructionDTO {\n");
    
    sb.append("    partyRole: ").append(toIndentedString(partyRole)).append("\n");
    sb.append("    settlementStatus: ").append(toIndentedString(settlementStatus)).append("\n");
    sb.append("    internalAcctCd: ").append(toIndentedString(internalAcctCd)).append("\n");
    sb.append("    instruction: ").append(toIndentedString(instruction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
