/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intellecteu.onesource.integration.services.client.onesource.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * ReturnDTO
 */



public class ReturnDTO {
  @JsonProperty("returnId")
  private String returnId = null;

  @JsonProperty("contractId")
  private String contractId = null;

  @JsonProperty("status")
  private ReturnStatusDTO status = null;

  @JsonProperty("executionVenue")
  private VenueDTO executionVenue = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  @JsonProperty("collateral")
  private CollateralDTO collateral = null;

  @JsonProperty("settlementType")
  private SettlementTypeDTO settlementType = null;

  @JsonProperty("settlement")
  private List<PartySettlementInstructionDTO> settlement = null;

  @JsonProperty("lastUpdateDatetime")
  private LocalDateTime lastUpdateDatetime = null;

  public ReturnDTO returnId(String returnId) {
    this.returnId = returnId;
    return this;
  }

   /**
   * Get returnId
   * @return returnId
  **/
  @Schema(description = "")
  public String getReturnId() {
    return returnId;
  }

  public void setReturnId(String returnId) {
    this.returnId = returnId;
  }

  public ReturnDTO contractId(String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId
  **/
  @Schema(required = true, description = "")
  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public ReturnDTO status(ReturnStatusDTO status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public ReturnStatusDTO getStatus() {
    return status;
  }

  public void setStatus(ReturnStatusDTO status) {
    this.status = status;
  }

  public ReturnDTO executionVenue(VenueDTO executionVenue) {
    this.executionVenue = executionVenue;
    return this;
  }

   /**
   * Get executionVenue
   * @return executionVenue
  **/
  @Schema(description = "")
  public VenueDTO getExecutionVenue() {
    return executionVenue;
  }

  public void setExecutionVenue(VenueDTO executionVenue) {
    this.executionVenue = executionVenue;
  }

  public ReturnDTO quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ReturnDTO collateral(CollateralDTO collateral) {
    this.collateral = collateral;
    return this;
  }

   /**
   * Get collateral
   * @return collateral
  **/
  @Schema(description = "")
  public CollateralDTO getCollateral() {
    return collateral;
  }

  public void setCollateral(CollateralDTO collateral) {
    this.collateral = collateral;
  }

  public ReturnDTO settlementType(SettlementTypeDTO settlementType) {
    this.settlementType = settlementType;
    return this;
  }

   /**
   * Get settlementType
   * @return settlementType
  **/
  @Schema(description = "")
  public SettlementTypeDTO getSettlementType() {
    return settlementType;
  }

  public void setSettlementType(SettlementTypeDTO settlementType) {
    this.settlementType = settlementType;
  }

  public ReturnDTO settlement(List<PartySettlementInstructionDTO> settlement) {
    this.settlement = settlement;
    return this;
  }

  public ReturnDTO addSettlementItem(PartySettlementInstructionDTO settlementItem) {
    if (this.settlement == null) {
      this.settlement = new ArrayList<>();
    }
    this.settlement.add(settlementItem);
    return this;
  }

   /**
   * Get settlement
   * @return settlement
  **/
  @Schema(description = "")
  public List<PartySettlementInstructionDTO> getSettlement() {
    return settlement;
  }

  public void setSettlement(List<PartySettlementInstructionDTO> settlement) {
    this.settlement = settlement;
  }

  public ReturnDTO lastUpdateDatetime(LocalDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @Schema(required = true, description = "")
  public LocalDateTime getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(LocalDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnDTO _return = (ReturnDTO) o;
    return Objects.equals(this.returnId, _return.returnId) &&
        Objects.equals(this.contractId, _return.contractId) &&
        Objects.equals(this.status, _return.status) &&
        Objects.equals(this.executionVenue, _return.executionVenue) &&
        Objects.equals(this.quantity, _return.quantity) &&
        Objects.equals(this.collateral, _return.collateral) &&
        Objects.equals(this.settlementType, _return.settlementType) &&
        Objects.equals(this.settlement, _return.settlement) &&
        Objects.equals(this.lastUpdateDatetime, _return.lastUpdateDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnId, contractId, status, executionVenue, quantity, collateral, settlementType, settlement, lastUpdateDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnDTO {\n");
    
    sb.append("    returnId: ").append(toIndentedString(returnId)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    executionVenue: ").append(toIndentedString(executionVenue)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    collateral: ").append(toIndentedString(collateral)).append("\n");
    sb.append("    settlementType: ").append(toIndentedString(settlementType)).append("\n");
    sb.append("    settlement: ").append(toIndentedString(settlement)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
