/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.intellecteu.onesource.integration.services.client.onesource.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
/**
 * TransactingPartyDTO
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-22T10:16:28.187392600Z[Europe/London]")

public class TransactingPartyDTO {
  @JsonProperty("partyRole")
  private PartyRoleDTO partyRole = null;

  @JsonProperty("party")
  private PartyDTO party = null;

  @JsonProperty("internalRef")
  private InternalReferenceDTO internalRef = null;

  public TransactingPartyDTO partyRole(PartyRoleDTO partyRole) {
    this.partyRole = partyRole;
    return this;
  }

   /**
   * Get partyRole
   * @return partyRole
  **/
  @Schema(description = "")
  public PartyRoleDTO getPartyRole() {
    return partyRole;
  }

  public void setPartyRole(PartyRoleDTO partyRole) {
    this.partyRole = partyRole;
  }

  public TransactingPartyDTO party(PartyDTO party) {
    this.party = party;
    return this;
  }

   /**
   * Get party
   * @return party
  **/
  @Schema(description = "")
  public PartyDTO getParty() {
    return party;
  }

  public void setParty(PartyDTO party) {
    this.party = party;
  }

  public TransactingPartyDTO internalRef(InternalReferenceDTO internalRef) {
    this.internalRef = internalRef;
    return this;
  }

   /**
   * Get internalRef
   * @return internalRef
  **/
  @Schema(required = true, description = "")
  public InternalReferenceDTO getInternalRef() {
    return internalRef;
  }

  public void setInternalRef(InternalReferenceDTO internalRef) {
    this.internalRef = internalRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactingPartyDTO transactingParty = (TransactingPartyDTO) o;
    return Objects.equals(this.partyRole, transactingParty.partyRole) &&
        Objects.equals(this.party, transactingParty.party) &&
        Objects.equals(this.internalRef, transactingParty.internalRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyRole, party, internalRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactingPartyDTO {\n");
    
    sb.append("    partyRole: ").append(toIndentedString(partyRole)).append("\n");
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("    internalRef: ").append(toIndentedString(internalRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
