package com.intellecteu.onesource.integration.model;

public enum EventType {
    ALLOCATION,
    BUYIN,
    BUYIN_APPROVE,
    BUYIN_CANCEL,
    BUYIN_COMPLETE,
    CONTRACT_CANCELED,
    CONTRACT_CANCEL_PENDING,
    CONTRACT_DECLINED,
    CONTRACT_PENDING,
    CONTRACT_OPENED,
    CONTRACT_PROPOSED,
    RECALL,
    RECALL_CANCEL,
    RERATE,
    RERATE_APPROVE,
    RERATE_CANCEL,
    RERATE_DECLINE,
    RETURN,
    RETURN_CANCEL,
    SPLIT,
    TRADE_AGREED,
    TRADE_CANCELED
}
