package com.intellecteu.onesource.integration.model;

public enum EventType {
    ALLOCATION,
    BUYIN,
    BUYIN_APPROVE,
    BUYIN_CANCEL,
    BUYIN_COMPLETE,
    CONTRACT,
    CONTRACT_APPROVE,
    CONTRACT_CANCEL,
    CONTRACT_DECLINE,
    RECALL,
    RECALL_CANCEL,
    RERATE,
    RERATE_APPROVE,
    RERATE_CANCEL,
    RERATE_DECLINE,
    RETURN,
    RETURN_CANCEL,
    SPLIT,
    TRADE,
    TRADE_AGREED,
    TRADE_CANCEL
}
