package com.intellecteu.onesource.integration.model;

public enum ProcessingStatus {
    NEW,
    SAVED,
    CREATED,
    PROCESSED,
    MATCHED_POSITION,
    MATCHED_CANCELED_POSITION,
    SPIRE_ISSUE,
    VALIDATED,
    TO_CANCEL,
    TO_DECLINE,
    RECONCILED,
    SPIRE_POSITION_CANCELED,
    CANCELED,
    PROPOSAL_CANCELED,
    DECLINED,
    PROPOSAL_DECLINED,
    APPROVED,
    PROPOSAL_APPROVED,
    ONESOURCE_ISSUE,
    UPDATED,
    SETTLED,
    SI_FETCHED
}
