package com.intellecteu.onesource.integration.model;

public enum ProcessingStatus {
    APPROVED,
    CANCELED,
    CREATED,
    DECLINED,
    DISCREPANCIES,
    MATCHED_CANCELED_POSITION,
    MATCHED_POSITION,
    NEW,
    ONESOURCE_ISSUE,
    PROCESSED,
    PROPOSAL_APPROVED,
    PROPOSAL_CANCELED,
    PROPOSAL_DECLINED,
    RECONCILED,
    TRADE_RECONCILED,
    SAVED,
    SETTLED,
    SI_FETCHED,
    SPIRE_ISSUE,
    SPIRE_POSITION_CANCELED,
    TO_CANCEL,
    TO_DECLINE,
    UPDATED,
    VALIDATED
}
