/*
 * Spire-Ref-Data-Service
 * Spire-Ref-Data-APIs
 *
 * OpenAPI spec version: 4.0
 * Contact: support.stonewain.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.intellecteu.onesource.integration.services.client.spire.dto.instruction;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.intellecteu.onesource.integration.services.client.spire.dto.AccountDTO;
import com.intellecteu.onesource.integration.services.client.spire.dto.CategoryDTO;
import com.intellecteu.onesource.integration.services.client.spire.dto.DepositoryDTO;
import com.intellecteu.onesource.integration.services.client.spire.dto.PositiontypeDTO;
import com.intellecteu.onesource.integration.services.client.spire.dto.SecurityDetailDTO;
import com.intellecteu.onesource.integration.services.client.spire.dto.SwiftbicDTO;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

/**
 * InstructionDTO
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-01-19T17:56:43.469+02:00")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InstructionDTO {

    @JsonProperty("__qualifiedName")
    private String qualifiedName = null;

    @JsonProperty("accountAddress1")
    private String accountAddress1 = null;

    @JsonProperty("accountAddress2")
    private String accountAddress2 = null;

    @JsonProperty("accountAddress3")
    private String accountAddress3 = null;

    @JsonProperty("accountAddress4")
    private String accountAddress4 = null;

    @JsonProperty("accountAddress5")
    private String accountAddress5 = null;

    @JsonProperty("accountDTO")
    private AccountDTO accountDTO = null;

    @JsonProperty("accountId")
    private Long accountId = null;

    @JsonProperty("accountName")
    private String accountName = null;

    @JsonProperty("accountShortName")
    private String accountShortName = null;

    @JsonProperty("agentAddress1")
    private String agentAddress1 = null;

    @JsonProperty("agentAddress2")
    private String agentAddress2 = null;

    @JsonProperty("agentAddress3")
    private String agentAddress3 = null;

    @JsonProperty("agentAddress4")
    private String agentAddress4 = null;

    @JsonProperty("agentAddress5")
    private String agentAddress5 = null;

    @JsonProperty("agentAltCode")
    private String agentAltCode = null;

    @JsonProperty("agentBicDTO")
    private SwiftbicDTO agentBicDTO = null;

    @JsonProperty("agentBicId")
    private Long agentBicId = null;

    @JsonProperty("agentName")
    private String agentName = null;

    @JsonProperty("agentSafe")
    private String agentSafe = null;

    @JsonProperty("altCode")
    private String altCode = null;

    @JsonProperty("bicDTO")
    private SwiftbicDTO bicDTO = null;

    @JsonProperty("bicId")
    private Long bicId = null;

    @JsonProperty("categoryDTO")
    private CategoryDTO categoryDTO = null;

    @JsonProperty("categoryId")
    private Integer categoryId = null;

    @JsonProperty("currencyId")
    private Integer currencyId = null;

    @JsonProperty("depoId")
    private Integer depoId = null;

    @JsonProperty("depositoryDTO")
    private DepositoryDTO depositoryDTO = null;

    @JsonProperty("instruction")
    private String instruction = null;

    @JsonProperty("instructionId")
    private Long instructionId = null;

    @JsonProperty("parentAccountDTO")
    private AccountDTO parentAccountDTO = null;

    @JsonProperty("parentAccountId")
    private Long parentAccountId = null;

    @JsonProperty("positionTypeId")
    private Integer positionTypeId = null;

    @JsonProperty("positiontypeDTO")
    private PositiontypeDTO positiontypeDTO = null;

    @JsonProperty("safe")
    private String safe = null;

    @JsonProperty("securityDetailDTO")
    private SecurityDetailDTO securityDetailDTO = null;

    @JsonProperty("securityId")
    private Long securityId = null;

    @JsonProperty("tradeTypeId")
    private Integer tradeTypeId = null;

    public InstructionDTO qualifiedName(String qualifiedName) {
        this.qualifiedName = qualifiedName;
        return this;
    }

    /**
     * Get qualifiedName
     *
     * @return qualifiedName
     **/
    @ApiModelProperty(value = "")
    public String getQualifiedName() {
        return qualifiedName;
    }

    public void setQualifiedName(String qualifiedName) {
        this.qualifiedName = qualifiedName;
    }

    public InstructionDTO accountAddress1(String accountAddress1) {
        this.accountAddress1 = accountAddress1;
        return this;
    }

    /**
     * Get accountAddress1
     *
     * @return accountAddress1
     **/
    @ApiModelProperty(value = "")
    public String getAccountAddress1() {
        return accountAddress1;
    }

    public void setAccountAddress1(String accountAddress1) {
        this.accountAddress1 = accountAddress1;
    }

    public InstructionDTO accountAddress2(String accountAddress2) {
        this.accountAddress2 = accountAddress2;
        return this;
    }

    /**
     * Get accountAddress2
     *
     * @return accountAddress2
     **/
    @ApiModelProperty(value = "")
    public String getAccountAddress2() {
        return accountAddress2;
    }

    public void setAccountAddress2(String accountAddress2) {
        this.accountAddress2 = accountAddress2;
    }

    public InstructionDTO accountAddress3(String accountAddress3) {
        this.accountAddress3 = accountAddress3;
        return this;
    }

    /**
     * Get accountAddress3
     *
     * @return accountAddress3
     **/
    @ApiModelProperty(value = "")
    public String getAccountAddress3() {
        return accountAddress3;
    }

    public void setAccountAddress3(String accountAddress3) {
        this.accountAddress3 = accountAddress3;
    }

    public InstructionDTO accountAddress4(String accountAddress4) {
        this.accountAddress4 = accountAddress4;
        return this;
    }

    /**
     * Get accountAddress4
     *
     * @return accountAddress4
     **/
    @ApiModelProperty(value = "")
    public String getAccountAddress4() {
        return accountAddress4;
    }

    public void setAccountAddress4(String accountAddress4) {
        this.accountAddress4 = accountAddress4;
    }

    public InstructionDTO accountAddress5(String accountAddress5) {
        this.accountAddress5 = accountAddress5;
        return this;
    }

    /**
     * Get accountAddress5
     *
     * @return accountAddress5
     **/
    @ApiModelProperty(value = "")
    public String getAccountAddress5() {
        return accountAddress5;
    }

    public void setAccountAddress5(String accountAddress5) {
        this.accountAddress5 = accountAddress5;
    }

    public InstructionDTO accountDTO(AccountDTO accountDTO) {
        this.accountDTO = accountDTO;
        return this;
    }

    /**
     * Get accountDTO
     *
     * @return accountDTO
     **/
    @ApiModelProperty(value = "")
    public AccountDTO getAccountDTO() {
        return accountDTO;
    }

    public void setAccountDTO(AccountDTO accountDTO) {
        this.accountDTO = accountDTO;
    }

    public InstructionDTO accountId(Long accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Get accountId
     *
     * @return accountId
     **/
    @ApiModelProperty(value = "")
    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public InstructionDTO accountName(String accountName) {
        this.accountName = accountName;
        return this;
    }

    /**
     * Get accountName
     *
     * @return accountName
     **/
    @ApiModelProperty(value = "")
    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public InstructionDTO accountShortName(String accountShortName) {
        this.accountShortName = accountShortName;
        return this;
    }

    /**
     * Get accountShortName
     *
     * @return accountShortName
     **/
    @ApiModelProperty(value = "")
    public String getAccountShortName() {
        return accountShortName;
    }

    public void setAccountShortName(String accountShortName) {
        this.accountShortName = accountShortName;
    }

    public InstructionDTO agentAddress1(String agentAddress1) {
        this.agentAddress1 = agentAddress1;
        return this;
    }

    /**
     * Get agentAddress1
     *
     * @return agentAddress1
     **/
    @ApiModelProperty(value = "")
    public String getAgentAddress1() {
        return agentAddress1;
    }

    public void setAgentAddress1(String agentAddress1) {
        this.agentAddress1 = agentAddress1;
    }

    public InstructionDTO agentAddress2(String agentAddress2) {
        this.agentAddress2 = agentAddress2;
        return this;
    }

    /**
     * Get agentAddress2
     *
     * @return agentAddress2
     **/
    @ApiModelProperty(value = "")
    public String getAgentAddress2() {
        return agentAddress2;
    }

    public void setAgentAddress2(String agentAddress2) {
        this.agentAddress2 = agentAddress2;
    }

    public InstructionDTO agentAddress3(String agentAddress3) {
        this.agentAddress3 = agentAddress3;
        return this;
    }

    /**
     * Get agentAddress3
     *
     * @return agentAddress3
     **/
    @ApiModelProperty(value = "")
    public String getAgentAddress3() {
        return agentAddress3;
    }

    public void setAgentAddress3(String agentAddress3) {
        this.agentAddress3 = agentAddress3;
    }

    public InstructionDTO agentAddress4(String agentAddress4) {
        this.agentAddress4 = agentAddress4;
        return this;
    }

    /**
     * Get agentAddress4
     *
     * @return agentAddress4
     **/
    @ApiModelProperty(value = "")
    public String getAgentAddress4() {
        return agentAddress4;
    }

    public void setAgentAddress4(String agentAddress4) {
        this.agentAddress4 = agentAddress4;
    }

    public InstructionDTO agentAddress5(String agentAddress5) {
        this.agentAddress5 = agentAddress5;
        return this;
    }

    /**
     * Get agentAddress5
     *
     * @return agentAddress5
     **/
    @ApiModelProperty(value = "")
    public String getAgentAddress5() {
        return agentAddress5;
    }

    public void setAgentAddress5(String agentAddress5) {
        this.agentAddress5 = agentAddress5;
    }

    public InstructionDTO agentAltCode(String agentAltCode) {
        this.agentAltCode = agentAltCode;
        return this;
    }

    /**
     * Get agentAltCode
     *
     * @return agentAltCode
     **/
    @ApiModelProperty(value = "")
    public String getAgentAltCode() {
        return agentAltCode;
    }

    public void setAgentAltCode(String agentAltCode) {
        this.agentAltCode = agentAltCode;
    }

    public InstructionDTO agentBicDTO(SwiftbicDTO agentBicDTO) {
        this.agentBicDTO = agentBicDTO;
        return this;
    }

    /**
     * Get agentBicDTO
     *
     * @return agentBicDTO
     **/
    @ApiModelProperty(value = "")
    public SwiftbicDTO getAgentBicDTO() {
        return agentBicDTO;
    }

    public void setAgentBicDTO(SwiftbicDTO agentBicDTO) {
        this.agentBicDTO = agentBicDTO;
    }

    public InstructionDTO agentBicId(Long agentBicId) {
        this.agentBicId = agentBicId;
        return this;
    }

    /**
     * Get agentBicId
     *
     * @return agentBicId
     **/
    @ApiModelProperty(value = "")
    public Long getAgentBicId() {
        return agentBicId;
    }

    public void setAgentBicId(Long agentBicId) {
        this.agentBicId = agentBicId;
    }

    public InstructionDTO agentName(String agentName) {
        this.agentName = agentName;
        return this;
    }

    /**
     * Get agentName
     *
     * @return agentName
     **/
    @ApiModelProperty(value = "")
    public String getAgentName() {
        return agentName;
    }

    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    public InstructionDTO agentSafe(String agentSafe) {
        this.agentSafe = agentSafe;
        return this;
    }

    /**
     * Get agentSafe
     *
     * @return agentSafe
     **/
    @ApiModelProperty(value = "")
    public String getAgentSafe() {
        return agentSafe;
    }

    public void setAgentSafe(String agentSafe) {
        this.agentSafe = agentSafe;
    }

    public InstructionDTO altCode(String altCode) {
        this.altCode = altCode;
        return this;
    }

    /**
     * Get altCode
     *
     * @return altCode
     **/
    @ApiModelProperty(value = "")
    public String getAltCode() {
        return altCode;
    }

    public void setAltCode(String altCode) {
        this.altCode = altCode;
    }

    public InstructionDTO bicDTO(SwiftbicDTO bicDTO) {
        this.bicDTO = bicDTO;
        return this;
    }

    /**
     * Get bicDTO
     *
     * @return bicDTO
     **/
    @ApiModelProperty(value = "")
    public SwiftbicDTO getBicDTO() {
        return bicDTO;
    }

    public void setBicDTO(SwiftbicDTO bicDTO) {
        this.bicDTO = bicDTO;
    }

    public InstructionDTO bicId(Long bicId) {
        this.bicId = bicId;
        return this;
    }

    /**
     * Get bicId
     *
     * @return bicId
     **/
    @ApiModelProperty(value = "")
    public Long getBicId() {
        return bicId;
    }

    public void setBicId(Long bicId) {
        this.bicId = bicId;
    }

    public InstructionDTO categoryDTO(CategoryDTO categoryDTO) {
        this.categoryDTO = categoryDTO;
        return this;
    }

    /**
     * Get categoryDTO
     *
     * @return categoryDTO
     **/
    @ApiModelProperty(value = "")
    public CategoryDTO getCategoryDTO() {
        return categoryDTO;
    }

    public void setCategoryDTO(CategoryDTO categoryDTO) {
        this.categoryDTO = categoryDTO;
    }

    public InstructionDTO categoryId(Integer categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    /**
     * Get categoryId
     *
     * @return categoryId
     **/
    @ApiModelProperty(value = "")
    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public InstructionDTO currencyId(Integer currencyId) {
        this.currencyId = currencyId;
        return this;
    }

    /**
     * Get currencyId
     *
     * @return currencyId
     **/
    @ApiModelProperty(value = "")
    public Integer getCurrencyId() {
        return currencyId;
    }

    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    public InstructionDTO depoId(Integer depoId) {
        this.depoId = depoId;
        return this;
    }

    /**
     * Get depoId
     *
     * @return depoId
     **/
    @ApiModelProperty(value = "")
    public Integer getDepoId() {
        return depoId;
    }

    public void setDepoId(Integer depoId) {
        this.depoId = depoId;
    }

    public InstructionDTO depositoryDTO(DepositoryDTO depositoryDTO) {
        this.depositoryDTO = depositoryDTO;
        return this;
    }

    /**
     * Get depositoryDTO
     *
     * @return depositoryDTO
     **/
    @ApiModelProperty(value = "")
    public DepositoryDTO getDepositoryDTO() {
        return depositoryDTO;
    }

    public void setDepositoryDTO(DepositoryDTO depositoryDTO) {
        this.depositoryDTO = depositoryDTO;
    }

    public InstructionDTO instruction(String instruction) {
        this.instruction = instruction;
        return this;
    }

    /**
     * Get instruction
     *
     * @return instruction
     **/
    @ApiModelProperty(value = "")
    public String getInstruction() {
        return instruction;
    }

    public void setInstruction(String instruction) {
        this.instruction = instruction;
    }

    public InstructionDTO instructionId(Long instructionId) {
        this.instructionId = instructionId;
        return this;
    }

    /**
     * Get instructionId
     *
     * @return instructionId
     **/
    @ApiModelProperty(value = "")
    public Long getInstructionId() {
        return instructionId;
    }

    public void setInstructionId(Long instructionId) {
        this.instructionId = instructionId;
    }

    public InstructionDTO parentAccountDTO(AccountDTO parentAccountDTO) {
        this.parentAccountDTO = parentAccountDTO;
        return this;
    }

    /**
     * Get parentAccountDTO
     *
     * @return parentAccountDTO
     **/
    @ApiModelProperty(value = "")
    public AccountDTO getParentAccountDTO() {
        return parentAccountDTO;
    }

    public void setParentAccountDTO(AccountDTO parentAccountDTO) {
        this.parentAccountDTO = parentAccountDTO;
    }

    public InstructionDTO parentAccountId(Long parentAccountId) {
        this.parentAccountId = parentAccountId;
        return this;
    }

    /**
     * Get parentAccountId
     *
     * @return parentAccountId
     **/
    @ApiModelProperty(value = "")
    public Long getParentAccountId() {
        return parentAccountId;
    }

    public void setParentAccountId(Long parentAccountId) {
        this.parentAccountId = parentAccountId;
    }

    public InstructionDTO positionTypeId(Integer positionTypeId) {
        this.positionTypeId = positionTypeId;
        return this;
    }

    /**
     * Get positionTypeId
     *
     * @return positionTypeId
     **/
    @ApiModelProperty(value = "")
    public Integer getPositionTypeId() {
        return positionTypeId;
    }

    public void setPositionTypeId(Integer positionTypeId) {
        this.positionTypeId = positionTypeId;
    }

    public InstructionDTO positiontypeDTO(PositiontypeDTO positiontypeDTO) {
        this.positiontypeDTO = positiontypeDTO;
        return this;
    }

    /**
     * Get positiontypeDTO
     *
     * @return positiontypeDTO
     **/
    @ApiModelProperty(value = "")
    public PositiontypeDTO getPositiontypeDTO() {
        return positiontypeDTO;
    }

    public void setPositiontypeDTO(PositiontypeDTO positiontypeDTO) {
        this.positiontypeDTO = positiontypeDTO;
    }

    public InstructionDTO safe(String safe) {
        this.safe = safe;
        return this;
    }

    /**
     * Get safe
     *
     * @return safe
     **/
    @ApiModelProperty(value = "")
    public String getSafe() {
        return safe;
    }

    public void setSafe(String safe) {
        this.safe = safe;
    }

    public InstructionDTO securityDetailDTO(SecurityDetailDTO securityDetailDTO) {
        this.securityDetailDTO = securityDetailDTO;
        return this;
    }

    /**
     * Get securityDetailDTO
     *
     * @return securityDetailDTO
     **/
    @ApiModelProperty(value = "")
    public SecurityDetailDTO getSecurityDetailDTO() {
        return securityDetailDTO;
    }

    public void setSecurityDetailDTO(SecurityDetailDTO securityDetailDTO) {
        this.securityDetailDTO = securityDetailDTO;
    }

    public InstructionDTO securityId(Long securityId) {
        this.securityId = securityId;
        return this;
    }

    /**
     * Get securityId
     *
     * @return securityId
     **/
    @ApiModelProperty(value = "")
    public Long getSecurityId() {
        return securityId;
    }

    public void setSecurityId(Long securityId) {
        this.securityId = securityId;
    }

    public InstructionDTO tradeTypeId(Integer tradeTypeId) {
        this.tradeTypeId = tradeTypeId;
        return this;
    }

    /**
     * Get tradeTypeId
     *
     * @return tradeTypeId
     **/
    @ApiModelProperty(value = "")
    public Integer getTradeTypeId() {
        return tradeTypeId;
    }

    public void setTradeTypeId(Integer tradeTypeId) {
        this.tradeTypeId = tradeTypeId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InstructionDTO instructionDTO = (InstructionDTO) o;
        return Objects.equals(this.qualifiedName, instructionDTO.qualifiedName) &&
            Objects.equals(this.accountAddress1, instructionDTO.accountAddress1) &&
            Objects.equals(this.accountAddress2, instructionDTO.accountAddress2) &&
            Objects.equals(this.accountAddress3, instructionDTO.accountAddress3) &&
            Objects.equals(this.accountAddress4, instructionDTO.accountAddress4) &&
            Objects.equals(this.accountAddress5, instructionDTO.accountAddress5) &&
            Objects.equals(this.accountDTO, instructionDTO.accountDTO) &&
            Objects.equals(this.accountId, instructionDTO.accountId) &&
            Objects.equals(this.accountName, instructionDTO.accountName) &&
            Objects.equals(this.accountShortName, instructionDTO.accountShortName) &&
            Objects.equals(this.agentAddress1, instructionDTO.agentAddress1) &&
            Objects.equals(this.agentAddress2, instructionDTO.agentAddress2) &&
            Objects.equals(this.agentAddress3, instructionDTO.agentAddress3) &&
            Objects.equals(this.agentAddress4, instructionDTO.agentAddress4) &&
            Objects.equals(this.agentAddress5, instructionDTO.agentAddress5) &&
            Objects.equals(this.agentAltCode, instructionDTO.agentAltCode) &&
            Objects.equals(this.agentBicDTO, instructionDTO.agentBicDTO) &&
            Objects.equals(this.agentBicId, instructionDTO.agentBicId) &&
            Objects.equals(this.agentName, instructionDTO.agentName) &&
            Objects.equals(this.agentSafe, instructionDTO.agentSafe) &&
            Objects.equals(this.altCode, instructionDTO.altCode) &&
            Objects.equals(this.bicDTO, instructionDTO.bicDTO) &&
            Objects.equals(this.bicId, instructionDTO.bicId) &&
            Objects.equals(this.categoryDTO, instructionDTO.categoryDTO) &&
            Objects.equals(this.categoryId, instructionDTO.categoryId) &&
            Objects.equals(this.currencyId, instructionDTO.currencyId) &&
            Objects.equals(this.depoId, instructionDTO.depoId) &&
            Objects.equals(this.depositoryDTO, instructionDTO.depositoryDTO) &&
            Objects.equals(this.instruction, instructionDTO.instruction) &&
            Objects.equals(this.instructionId, instructionDTO.instructionId) &&
            Objects.equals(this.parentAccountDTO, instructionDTO.parentAccountDTO) &&
            Objects.equals(this.parentAccountId, instructionDTO.parentAccountId) &&
            Objects.equals(this.positionTypeId, instructionDTO.positionTypeId) &&
            Objects.equals(this.positiontypeDTO, instructionDTO.positiontypeDTO) &&
            Objects.equals(this.safe, instructionDTO.safe) &&
            Objects.equals(this.securityDetailDTO, instructionDTO.securityDetailDTO) &&
            Objects.equals(this.securityId, instructionDTO.securityId) &&
            Objects.equals(this.tradeTypeId, instructionDTO.tradeTypeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(qualifiedName, accountAddress1, accountAddress2, accountAddress3, accountAddress4,
            accountAddress5, accountDTO, accountId, accountName, accountShortName, agentAddress1, agentAddress2,
            agentAddress3, agentAddress4, agentAddress5, agentAltCode, agentBicDTO, agentBicId, agentName, agentSafe,
            altCode, bicDTO, bicId, categoryDTO, categoryId, currencyId, depoId, depositoryDTO, instruction,
            instructionId, parentAccountDTO, parentAccountId, positionTypeId, positiontypeDTO, safe, securityDetailDTO,
            securityId, tradeTypeId);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InstructionDTO {\n");

        sb.append("    qualifiedName: ").append(toIndentedString(qualifiedName)).append("\n");
        sb.append("    accountAddress1: ").append(toIndentedString(accountAddress1)).append("\n");
        sb.append("    accountAddress2: ").append(toIndentedString(accountAddress2)).append("\n");
        sb.append("    accountAddress3: ").append(toIndentedString(accountAddress3)).append("\n");
        sb.append("    accountAddress4: ").append(toIndentedString(accountAddress4)).append("\n");
        sb.append("    accountAddress5: ").append(toIndentedString(accountAddress5)).append("\n");
        sb.append("    accountDTO: ").append(toIndentedString(accountDTO)).append("\n");
        sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
        sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
        sb.append("    accountShortName: ").append(toIndentedString(accountShortName)).append("\n");
        sb.append("    agentAddress1: ").append(toIndentedString(agentAddress1)).append("\n");
        sb.append("    agentAddress2: ").append(toIndentedString(agentAddress2)).append("\n");
        sb.append("    agentAddress3: ").append(toIndentedString(agentAddress3)).append("\n");
        sb.append("    agentAddress4: ").append(toIndentedString(agentAddress4)).append("\n");
        sb.append("    agentAddress5: ").append(toIndentedString(agentAddress5)).append("\n");
        sb.append("    agentAltCode: ").append(toIndentedString(agentAltCode)).append("\n");
        sb.append("    agentBicDTO: ").append(toIndentedString(agentBicDTO)).append("\n");
        sb.append("    agentBicId: ").append(toIndentedString(agentBicId)).append("\n");
        sb.append("    agentName: ").append(toIndentedString(agentName)).append("\n");
        sb.append("    agentSafe: ").append(toIndentedString(agentSafe)).append("\n");
        sb.append("    altCode: ").append(toIndentedString(altCode)).append("\n");
        sb.append("    bicDTO: ").append(toIndentedString(bicDTO)).append("\n");
        sb.append("    bicId: ").append(toIndentedString(bicId)).append("\n");
        sb.append("    categoryDTO: ").append(toIndentedString(categoryDTO)).append("\n");
        sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
        sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
        sb.append("    depoId: ").append(toIndentedString(depoId)).append("\n");
        sb.append("    depositoryDTO: ").append(toIndentedString(depositoryDTO)).append("\n");
        sb.append("    instruction: ").append(toIndentedString(instruction)).append("\n");
        sb.append("    instructionId: ").append(toIndentedString(instructionId)).append("\n");
        sb.append("    parentAccountDTO: ").append(toIndentedString(parentAccountDTO)).append("\n");
        sb.append("    parentAccountId: ").append(toIndentedString(parentAccountId)).append("\n");
        sb.append("    positionTypeId: ").append(toIndentedString(positionTypeId)).append("\n");
        sb.append("    positiontypeDTO: ").append(toIndentedString(positiontypeDTO)).append("\n");
        sb.append("    safe: ").append(toIndentedString(safe)).append("\n");
        sb.append("    securityDetailDTO: ").append(toIndentedString(securityDetailDTO)).append("\n");
        sb.append("    securityId: ").append(toIndentedString(securityId)).append("\n");
        sb.append("    tradeTypeId: ").append(toIndentedString(tradeTypeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

