package com.intellecteu.onesource.integration.model.enums;

public enum RecordType {
    GET_COUNTERPARTY_SETTLEMENT_INSTRUCTION,
    LOAN_CONTRACT_SETTLED,
    LOAN_CONTRACT_PROPOSAL_APPROVED,
    LOAN_CONTRACT_PROPOSAL_CANCELED,
    LOAN_CONTRACT_PROPOSAL_CREATED,
    LOAN_CONTRACT_PROPOSAL_DECLINED,
    LOAN_CONTRACT_PROPOSAL_DISCREPANCIES,
    LOAN_CONTRACT_PROPOSAL_MATCHED_POSITION,
    LOAN_CONTRACT_PROPOSAL_MATCHING_CANCELED_POSITION,
    LOAN_CONTRACT_PROPOSAL_VALIDATED,
    LOAN_CONTRACT_PROPOSAL_UNMATCHED,
    POSITION_CANCELED,
    POSITION_CANCELED_SUBMITTED,
    POSITION_UNMATCHED,
    RERATE_PROPOSAL_MATCHED,
    RERATE_PROPOSAL_MATCHED_RERATE_TRADE,
    RERATE_PROPOSAL_PENDING_APPROVAL,
    RERATE_PROPOSAL_UNMATCHED,
    RERATE_TRADE_CREATED,
    TRADE_AGREEMENT_CANCELED,
    TRADE_AGREEMENT_CREATED,
    TRADE_AGREEMENT_DISCREPANCIES,
    TRADE_AGREEMENT_RECONCILED,
    TRADE_AGREEMENT_MATCHED_POSITION,
    TRADE_AGREEMENT_MATCHED_CANCELED_POSITION,
    TECHNICAL_EXCEPTION_1SOURCE,
    TECHNICAL_EXCEPTION_SPIRE

}
