package com.intellecteu.onesource.integration.enums;

public enum IntegrationSubProcess {
  APPROVE_LOAN_CONTRACT_PROPOSAL,
  CANCEL_LOAN_CONTRACT_PROPOSAL,
  DECLINE_LOAN_CONTRACT_PROPOSAL,
  GET_1SOURCE_EVENTS,
  GET_LOAN_CONTRACT_PROPOSAL,
  GET_PARTICIPANTS_LIST,
  GET_POSITIONS_PENDING_CONFIRMATION,
  GET_POSITION_SETTLEMENT,
  GET_SETTLEMENT_INSTRUCTIONS,
  GET_TRADE_AGREEMENT,
  GET_TRADE_CANCELATION,
  POST_LOAN_CONTRACT_PROPOSAL,
  POST_LOAN_CONTRACT_PROPOSAL_UPDATE,
  POST_LOAN_CONTRACT_UPDATE,
  POST_PARTICIPANT_ADDITION_OR_REMOVAL,
  POST_POSITION_UPDATE,
  POST_SETTLEMENT_INSTRUCTION_UPDATE,
  RECONCILE_TRADE_AGREEMENT,
  VALIDATE_LOAN_CONTRACT_PROPOSAL
}
