package com.intellecteu.onesource.integration.enums;

public enum RecordType {

  LOAN_CONTRACT_PROPOSAL_APPROVED,
  LOAN_CONTRACT_PROPOSAL_CANCELED,
  LOAN_CONTRACT_PROPOSAL_CREATED,
  LOAN_CONTRACT_PROPOSAL_DECLINED,
  LOAN_CONTRACT_PROPOSAL_DISCREPANCIES,
  LOAN_CONTRACT_PROPOSAL_MATCHING_CANCELED_POSITION,
  LOAN_CONTRACT_PROPOSAL_VALIDATED,
  TRADE_AGREEMENT_CANCELED,
  TRADE_AGREEMENT_CREATED,
  TRADE_AGREEMENT_DISCREPANCIES,
  TRADE_AGREEMENT_RECONCILED,
  TECHNICAL_EXCEPTION_1SOURCE,
  TECHNICAL_EXCEPTION_SPIRE,
  TRADE_AGREEMENT_MATCHED_POSITION,
  LOAN_CONTRACT_PROPOSAL_MATCHED_POSITION

}
